### ISSUE TITLE
Server Side Rendering window is not defined

### ISSUE THREAD

**Issue by dav-is** [awslabs/aws-mobile-appsync-sdk-js#10]
I tried implementing SSR and it throws an error about the window not being defined. Looks like `paho-client` doesn’t support SSR.

**Comment by cgarvis** [comment]
I'm not able to find a way to setup `global.window` before importing `aws-appsync` in a next.js project.

**Comment by cgarvis** [comment]
Thoughts on using [MQTT.js](https://github.com/mqttjs/MQTT.js) instead of Paho?

**Comment by sakhmedbayev** [comment]
@dav-is, have you been able to accomplish anything on this issue?

**Comment by dav-is** [comment]
@sakhmedbayev Honestly I dropped AWS Appsync in favor of Google’s cloud and just running a regular graphql server.

**Comment by manueliglesias** [comment]
Hi!

We are actively working on removing dependencies on the window object to enable server side rendering without having to polyfill stuff. Stay tuned.

If you're curious how this would work in the future (please understand this is experimental and requires for now unpublished modules and unmerged pull requests to third party repos), you can take a look at [manueliglesias/urban-pancake](https://github.com/manueliglesias/urban-pancake) (a nextjs web app I am using to test stuff), specifically this piece https://github.com/manueliglesias/urban-pancake/blob/61f167f99793d6573adcf577d975578353d5b70c/lib/initApollo.js#L13-L31

**Comment by growak** [comment]
Hi @manueliglesias, any progress or deadline on the server-sider version ? Thx

**Comment by undefobj** [comment]
@growak @dav-is @cgarvis @sakhmedbayev  we have a resolution however the dependent library that we use will not be updated until the end of next month. [You can view the PR here](https://github.com/eclipse/paho.mqtt.javascript/pull/153). We are investigating ways to potentially get a published version sooner and talking to the contributors of that project. Please be patient as we work through the distribution process.

**Comment by stoffern** [comment]
Why is this issue closed?

**Comment by Necmttn** [comment]
?Any update on this, anyone manages to solve it somehow?
