### ISSUE TITLE
how to make this support for server side render?

### ISSUE THREAD

**Issue by xfkj** [awslabs/aws-mobile-appsync-sdk-js#104]
how to make this support for server side render?

**Comment by tgorka** [comment]
What do you mean by "support for server". If you mean that `window` is not working, then I made #110  And it's working for me on the server site.

**Comment by manueliglesias** [comment]
Thank you for your contribution @xfkj !! 😃 

We are actively working on removing dependencies on the window object to enable server side rendering without having to polyfill stuff. Stay tuned.

If you're curious how this would work in the future (please understand this is experimental and requires for now unpublished modules and unmerged pull requests to third party repos), you can take a look at [manueliglesias/urban-pancake](https://github.com/manueliglesias/urban-pancake) (a nextjs web app I am using to test stuff), specifically this piece https://github.com/manueliglesias/urban-pancake/blob/61f167f99793d6573adcf577d975578353d5b70c/lib/initApollo.js#L13-L31

**Comment by lolcoolkat** [comment]
Any idea when it will be ready @manueliglesias :) Looking forward to it!!!
