### ISSUE TITLE
"ReferenceError: scope is not defined"

### ISSUE THREAD

**Issue by dmawrey** [awslabs/aws-mobile-appsync-sdk-js#111]
After updating to aws-appsync@1.0.16, the error below is thrown on every query, causing the query to fail. The issue is resolved after downgrading to aws-appsync@1.0.15.
```
Uncaught (in promise) ReferenceError: scope is not defined
    at Function.sign (signer.js:208)
    at Object.<anonymous> (auth-link.js:150)
    at step (auth-link.js:50)
    at Object.next (auth-link.js:31)
    at fulfilled (auth-link.js:22)
```

**Comment by cmath** [comment]
Same here. The only way to get it working is to change authentication type to API key.

**Comment by cmath** [comment]
@tgorka Thanks for that. Hope it gets merged soon.
