### ISSUE TITLE
unsubscribing does not close node process

### ISSUE THREAD

**Issue by Xiphe** [awslabs/aws-mobile-appsync-sdk-js#113]
I was following the official [guide on how to use the sdk in nodejs](https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-javascript.html).

Given I am in a nodejs script
And I have an observed subscription
```js
const observable = client.subscribe({ query: subquery });

const handle = observable.subscribe({
    next: realtimeResults,
    complete: console.log,
    error: console.log,
});
```

When I call `handle.unsubscribe()`
Then I expect the script to finish and the node process should close automatically
BUT the node process stays active (`realtimeResults` is not called though)

**Comment by manueliglesias** [comment]
Hi @Xiphe 

Thanks for opening this issue, I'll be taking a look

**Comment by uchar** [comment]
@manueliglesias I think this problem still exist, using unsubscribe does not kill jest test
