### ISSUE TITLE
GraphQL Query Runs Sucessfully One Time and Fails To Run Again

### ISSUE THREAD

**Issue by reggie3** [awslabs/aws-mobile-appsync-sdk-js#115]
I'm using the basic client configuration from the example on the first page of this repo:

```
const client = new AWSAppSyncClient({
  url: appSyncConfig.graphqlEndpoint,
  region: appSyncConfig.region,
  auth: {
    type: appSyncConfig.authenticationType,
    apiKey: appSyncConfig.apiKey,
  }
});
```

But without the `<Rehydrated>` component, and with a Redux `<Provider>` component.  The highest level parent component is wrapped like this
```
<Provider store={store}>
  <ApolloProvider client={client}>
    <App/>
  </ApolloProvider>
</Provider>
```

I've tried swapping the order for the Provider and ApolloProvider, but that did not change the result.

The problem is that the query runs successfully one time but, doesn't run again.  
The AppSync's CloudWatch logs show the initial successful query, but show no further query attempts. That leads me to believe that the problem is due to something on the client.

I've set the `fetchPolicy` on the query to 'network-only' with no results.
```
const mapDataToProps = graphql(GET_ALL_STORIES, {
  name: 'getAllStories',
  options: { fetchPolicy: 'network-only' }
});
```

I've confirmed that the named query "getAllStories" does actually exist on the component by inspecting the component in the Chrome debugger. The query props `NetworkStatus` and loading properties remain at `1` and `true` the entire time, and no response is ever received.

Versions Currently Used:

aws-appsync: 1.0.17
Apollo-client: 2.2.8
react-Apollo: 2.1.3
 

**Edit**:
Additional information.  This is happening in a react-native program created with Expo.  Reloading the program by shaking the device and selecting "Reload" results in the above behavior.  However, restarting Expo after a forced shut down, and running the program again causes the query to be refetched as desired.

I am not sure if this is a problem with aws-mobile-appsync-sdk or Expo, so I've also posted about it on their help forum [here](https://forums.expo.io/t/strange-caching-behavior-using-aws-appsync/9377)

**Comment by lolcoolkat** [comment]
You're better off posting the question here https://forums.aws.amazon.com/forum.jspa?forumID=280 

Not sure sure why but the devs don't seem to be very active on this repo. Kinda discouraging since there have been quite a number of bugs in the past few weeks which have yet to be resolved.

**Comment by manueliglesias** [comment]
Hi @reggie3 , @lolcoolkat 

`<Rehydrated>` is required when using the offline capabilities. This component basically delays rendering of its children until the cache is populated back from the persisted storage (localStorage in browser, AsyncStorage in RN).

Another option you can try just to start discarding potential issues is to disable the offline behaviour in the client:

```diff
const client = new AWSAppSyncClient({
  url: appSyncConfig.graphqlEndpoint,
  region: appSyncConfig.region,
  auth: {
    type: appSyncConfig.authenticationType,
    apiKey: appSyncConfig.apiKey,
  },
+  disableOffline: true
});
```

**Comment by reggie3** [comment]
@manueliglesias Thanks. I will give it a try when I get back to that project again, and let you know how it turned out.

**Comment by manueliglesias** [comment]
Closing this for now, please feel free to re-open if the issue persists
