### ISSUE TITLE
CloudWatch Log Units

### ISSUE THREAD

**Issue by richardzyx** [awslabs/aws-mobile-appsync-sdk-js#116]
Hi,

I was trying to understand my query performance, and enabled the ALL logging option. For a specific case, here's the execution summary:
```
{
    "version": 1,
    "startTime": "2018-05-01T21:13:10.784Z",
    "endTime": "2018-05-01T21:13:10.841Z",
    "duration": 56649619,
    "parsing": {
        "startOffset": 102051,
        "duration": 67896
    },
    "validation": {
        "startOffset": 223303,
        "duration": 115733
    }
}
``` 

What units are duration and startOffset in? I imagine they would be some sort of counter from within the execution since the logged latency for this query is only 128 ms.

Thanks!

**Comment by vrsn** [comment]
Hi Richard, the tracing logs are emitted per the format documented at [apollo-tracing](https://github.com/apollographql/apollo-tracing).

From the documentation:

* The duration of a request is in nanoseconds, relative to the request start.

* The startOffset of parsing, validation, or a resolver call is in nanoseconds, relative to the request start.

**Comment by richardzyx** [comment]
Hi Shankar,

Thanks for your prompt reply! I would put that on the dev guide so people can find it our more easily =]

**Comment by vrsn** [comment]
Yep, that is a good suggestion. We will add it soon.
