### ISSUE TITLE
MappingTemplate : Transformation too large

### ISSUE THREAD

**Issue by anthonysist** [awslabs/aws-mobile-appsync-sdk-js#124]
My Specific error:

`{"data":{"sync":null},"errors":[{"path":["sync"],"data":null,"errorType":"MappingTemplate","errorInfo":null,"locations":[{"line":2,"column":3}],"message":"Transformation too large"}]}`

There seem to be some instances where a large .json body throws this error. Any workaround to this besides breaking up the data?

**Comment by keyfu** [comment]
Could you solve the problem? I also feel the same and I could not. Can you help me?

**Comment by bitfrost** [comment]
I am running into this as well in query console,  4.3  meg json response from a lambda.   Lambda runs fine on its own.

**Comment by jfdoube** [comment]
Any updates here ?

**Comment by bitfrost** [comment]
I got this from aws support
"The AppSync team has responded and confirmed that there is a 1MB limit. They are considering increasing this limit and are working to have this limit documented. Please understand that AWS Support cannot provide ETAs for when or if this increase will go through.

If there are additional questions regarding this matter, please feel free to reach back."

**Comment by manueliglesias** [comment]
Closing issue as it is a service related question that appears to be answered.

**Comment by reberthkss** [comment]
Any updates?

**Comment by awadhwanan** [comment]
I often feel the amplify and the app-sync ecosystem is completely broken. I mean when there is a support for integration with lambda and the lambdas can run for more than a min why would app-sync fail and if the lambda can give back the response why cant the app-sync. AWS does a lot a thing right but they only do it right till like 73.64%
