### ISSUE TITLE
IE 11 support

### ISSUE THREAD

**Issue by demsey2** [awslabs/aws-mobile-appsync-sdk-js#127]
I can't believe I am saying this but is there any way to get that working with IE11. The main problem is lack of "fetch" in IE11. 

I tried to add unfetch polyfill, create a link and attach to optioins, there were a few other issues but I managed to avoid any exceptions in IE, however, that didn't help. My app doesn't work at all.

**Comment by dani-media** [comment]
Find a fix?

**Comment by demsey2** [comment]
make sure the other things are working fine, I had a problem with Object.assign

**Comment by manueliglesias** [comment]
Hi @demsey2 

Were you able to fix your issue? Did transpiling help you?

**Comment by demsey2** [comment]
yes I did but the problem wasn't "fetch", it was something else, try run the app without fetching data if possible and check if everything else is working fine
