### ISSUE TITLE
How to get up and running with Vue + Apollo?

### ISSUE THREAD

**Issue by ffxsam** [awslabs/aws-mobile-appsync-sdk-js#13]
If I understand correctly, instead of using Apollo's method of connecting to a GraphQL endpoint, are we to use AppSync's instead? Is there any specific way we should set up AppSync for use in a Vue project?

**Comment by manueliglesias** [comment]
Hi @ffxsam 

You would use this SDK the very same way you'd useApollo (see https://github.com/akryum/vue-apollo#installation for Vue.js specifics) but passing the AppSyncClient instead.
