### ISSUE TITLE
in Angular5 problem

### ISSUE THREAD

**Issue by raulobba21** [awslabs/aws-mobile-appsync-sdk-js#131]
Hello team. 
I made a sample app with this sdk.
I don't Know what problem is.

Here is my code
`
constructor(private appsync: AppsyncService) { }

  ngOnInit() {
    this.appsync.hc().then(client => {
      const observable = client.watchQuery({
        query: ListEventsQuery,
        fetchPolicy: 'cache-and-network'
      });

      observable.subscribe(({data}) => {

        if (data) {
          console.log(data);
        }
      });
    });
  }
`
-component.ts

`
const config = {
  url: "my_key.appsync-api.us-west-2.amazonaws.com/graphql",
  region: "us-west-2",
  auth: {
    type: "API_KEY",
    apiKey: "my_api_key"
  }
}

@Injectable()
export class AppsyncService {
  hc;
  constructor() {
    const client = new AWSAppSyncClient(config);
    this.hc = client.hydrated;
  }
}
`
- appsync.service.ts

And Here is my query

import gql from 'graphql-tag';

export default gql`
query ListEvents($limit: Int, $nextToken: String) {
    listEvents(limit: $limit, nextToken: $nextToken) {
        items {
            ...Event
        }
        nextToken
    }
}`;

If I run this code I met this error
`Unhandled error Network error: Can't find field listEvents({}) on object (ROOT_QUERY) undefined. Error: Network error: Can't find field listEvents({}) on object (ROOT_QUERY) undefined.
    at new ApolloError (webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/errors/ApolloError.js:36:28)
    at eval (webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/core/QueryManager.js:287:41)
    at eval (webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/core/QueryManager.js:668:17)
    at Array.forEach (<anonymous>)
    at eval (webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/core/QueryManager.js:667:18)
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/core/QueryManager.js:662:22)
    at eval (webpack-internal:///./node_modules/aws-appsync/node_modules/apollo-client/core/QueryManager.js:236:31)
    at ZoneDelegate.invoke (webpack-internal:///./node_modules/zone.js/dist/zone.js:388:26)
    at Object.onInvoke (webpack-internal:///./node_modules/@angular/core/esm5/core.js:4976:33)`

How can I solve it? Please Help!
Thank you.

**Comment by jeremyputeaux** [comment]
Hi! Did you solved this? I'm experimenting the same thing on angular v6.

**Comment by haverchuck** [comment]
@jeremyputeaux  and @raulobba21 -  I susupect this must have something to do with how your query is formed.  Testing on both Angular 5 and Angular 7, I successfully used @raulobba21 's code to successfully fetch subscription data.  

My service:
```
import { Injectable } from '@angular/core';
import aws_config from '../aws-exports';
import Auth from '@aws-amplify/auth';
import { AWSAppSyncClient } from 'aws-appsync';

import Amplify from 'aws-amplify';
Amplify.configure(aws_config);

let token;

Auth.currentSession().then((res) => {
  token = res.getIdToken();
})
.catch(e => console.log(e));

const config = {
  url: aws_config.aws_appsync_graphqlEndpoint,
  region: 'us-west-2',
  auth: {
    type: aws_config.aws_appsync_authenticationType,
    jwtToken: async () => (await (Auth.currentSession() as any)).idToken.jwtToken
  }};

  console.log(config);

  @Injectable()
  export class AppsyncService {
    client: any;
    hc: any;
    constructor() {
      this.client = new AWSAppSyncClient(config);
      this.hc = this.client.hydratedPromise;
    }

  }
```

My component
```
import { Injectable } from '@angular/core';
import aws_config from '../aws-exports';
import Auth from '@aws-amplify/auth';
import { AWSAppSyncClient } from 'aws-appsync';

import Amplify from 'aws-amplify';
Amplify.configure(aws_config);

let token;

Auth.currentSession().then((res) => {
  token = res.getIdToken();
})
.catch(e => console.log(e));

const config = {
  url: aws_config.aws_appsync_graphqlEndpoint,
  region: 'us-west-2',
  auth: {
    type: aws_config.aws_appsync_authenticationType,
    jwtToken: async () => (await (Auth.currentSession() as any)).idToken.jwtToken
  }};

  console.log(config);

  @Injectable()
  export class AppsyncService {
    client: any;
    hc: any;
    constructor() {
      this.client = new AWSAppSyncClient(config);
      this.hc = this.client.hydratedPromise;
    }

  }
```

Obviously I'm using Cognito authentication instead of an API Key and hydratedPromise for the client.  Maybe you could try using a very simple query and work backwards from there?

**Comment by elorzafe** [comment]
I will close this for now, but feel free @raulobba21 or @jeremyputeaux to reopen this issue or to create a new one.
