### ISSUE TITLE
Server errors and optimisticResponse rollback

### ISSUE THREAD

**Issue by deftomat** [awslabs/aws-mobile-appsync-sdk-js#133]
When mutation with an optimisticResponse fails, optimistic response should be removed from a cache.

We have a simple mutation component
```tsx
<Mutation mutation={updatePersonalDetailsMutation}>
  {(mutate, { loading, error }) => (
    <PersonalDetailsForm
      submitting={loading}
      errors={error ? [{ message: 'Unexpected error during submitting' }] : []}
      submit={values =>
        mutate({
          variables: { input: values },
          optimisticResponse: {
            updatePersonalDetails: {
              __typename: 'Person',
              id: 1,
              firstName: 'John',
              lastName: 'Doe'
            }
          }
        })
      }
    />
  )}
</Mutation>
```

When an offline link is enabled and this mutation returns error, then `error` is undefined all the time and `optimisticResponse` is never reverted.

Also, `loading` flag is set to true and then immediately to false. I don't think that this behaviour is excepted by people which are trying to use this library.

So, we have no error handling and we cannot know, if a mutation is in flight or not. 

All of these issues can be avoided by disabling the offline support. However, then we will lost a persistent cache.

**Comment by manueliglesias** [comment]
Hi @deftomat 

We are currently working on some improvements in these areas. If you want to try them now and be a beta tester of them, they are published in npm under the deepdish tag.

`yarn add aws-appsync@deepdish aws-appsync-react@deepdish`

We would love to hear your feedback!

**Comment by deftomat** [comment]
@manueliglesias Thanks, I will try it next week and I'll let you know.

**Comment by deftomat** [comment]
@manueliglesias Optimistic response rollback is working. However, there are still no errors and a loading state is probably incorrect. See #140.
