### ISSUE TITLE
Offline support swallows all server errors and loading state

### ISSUE THREAD

**Issue by deftomat** [awslabs/aws-mobile-appsync-sdk-js#140]
As mentioned in #133, `error` in Mutation component is always undefined when an offline support is enabled. Also, a `loading` flag is set to false even when request is still in flight. 

I'm not sure if this is an intended behaviour or not but it's definitely different from a basic Apollo Client.

I'm using `v1.0.22`

**Comment by ojdx** [comment]
I can see the error returning on the response in the  apollo-link-error but not on the mutation

**Comment by menkveldj** [comment]
@ojdx +1 on this.

**Comment by jakubkoci** [comment]
I have the same problem. I've tried it with regular `ApolloClient` component, and there was an invalid data error thrown correctly (empty string in `note` attribute for example). The same code with `AWSAppSyncClient` didn't throw anything. This issue occurs also on React Native.

**Comment by elorzafe** [comment]
We have fixed this on the latest release (aws-appsync@1.4.0) I will close the issue for now, but feel free to create a new issue if this problem persist.
