### ISSUE TITLE
Loading state stuck on true and network request is never made

### ISSUE THREAD

**Issue by CodySwannGT** [awslabs/aws-mobile-appsync-sdk-js#150]
Hey guys,

Looks like [this bug](https://github.com/apollographql/apollo-client/issues/2687) has made it downstream

We managed to get around it by disabling offline mode, but that's not idea.

Additionally, even with offline mode disabled, the problem reappeared when trying to integrate with link-state following the example you provided.

       "apollo-client": "^2.3.1",
        "apollo-link": "^1.2.2",
        "apollo-link-state": "^0.4.1",
        "aws-amplify": "^0.4.4",
        "aws-amplify-react-native": "^0.2.15",
        "aws-appsync": "^1.0.23",
        "aws-appsync-react": "^1.0.14",
        "graphql": "^0.13.2",
        "graphql-tag": "^2.8.0",
        "react-apollo": "^2.1.4",

**Comment by arrygoo** [comment]
I'm experiencing this too :(

**Comment by rogueturnip** [comment]
Also seeing this bug now.

**Comment by jrounsav** [comment]
Also seeing

**Comment by manueliglesias** [comment]
Closing this since it appears to be fixed in newer versions of `react-apollo`

Let us know if you still have this issue to re-open it and investigate.

**Comment by ShivashankarL** [comment]
Same issue in   "@apollo/client": "^3.4.13",
