### ISSUE TITLE
Unsubscribe never closes the link

### ISSUE THREAD

**Issue by lexnat187** [awslabs/aws-mobile-appsync-sdk-js#152]
After calling unsubscribe on the subscription observer I would expect that to be fully closed and the resources released. This seems to never happen and results in eventually exceeding the limit of 50 subscriptions per account, resulting in the error I raised in #145.

To replicate this establish a client and create 25 subscriptions, then call unsubscribe on them before creating a further 26 subscriptions. Once you exceed 50 the next subscription will not be created.

I'm using these versions:
"aws-appsync": "^1.0.22",
"aws-appsync-react": "^1.0.13",
"aws-sdk": "^2.251.1",
"graphql-tag": "^2.9.2",
"react-apollo": "^2.1.4",

**Comment by manueliglesias** [comment]
This should be fixed. Please feel free to comment here if you still see the problem with the latest version and I'll re-open the issue
