### ISSUE TITLE
Vue.js - Passing parameters to query example

### ISSUE THREAD

**Issue by vahdet** [awslabs/aws-mobile-appsync-sdk-js#154]
Is there an example for **passing parameters to query** by Vue.js?

**Comment by iskanderbroere** [comment]
https://akryum.github.io/vue-apollo/guide/apollo/queries.html#query-with-parameters

**Comment by vahdet** [comment]
I ended up with using GraphQL Client of AWS Amplify: https://aws-amplify.github.io/amplify-js/media/api_guide.html
