### ISSUE TITLE
Fetches using no-cache broken

### ISSUE THREAD

**Issue by fcobia** [awslabs/aws-mobile-appsync-sdk-js#169]
It ruins out that fetches where the fetch policy is set to no-cache always return null data. This seems to be a known issue and fixed in new versions of apollo-client.

https://github.com/apollographql/apollo-client/issues/3030

**Comment by jsphweid** [comment]
I'm not sure it looks fixed from that thread. I'm getting by for now by using 'network-only'

**Comment by fcobia** [comment]
The problem there is that is still writes to the cache and eventually the cache will fill up and the app will crash.

**Comment by elorzafe** [comment]
Hi @fcobia you still have this problem?

**Comment by fcobia** [comment]
Unless there is a newer version of the library then I would assume that the problem is still there. Is there a new version I should check?

**Comment by manueliglesias** [comment]
Hey @fcobia 

Are you still having this issue with the latest version?

**Comment by manueliglesias** [comment]
This is the latest version as of today:

```bash
~ npm info aws-appsync name "dist-tags".latest
name = 'aws-appsync'
dist-tags.latest = '1.7.0'
```

**Comment by elorzafe** [comment]
I will close this for now, but feel free @fcobia or @jsphweid  to reopen this issue or to create a new one.
