### ISSUE TITLE
Add a CHANGELOG File?

### ISSUE THREAD

**Issue by jessedoyle** [awslabs/aws-mobile-appsync-sdk-js#171]
Hi all,

Thanks for the awesome packages! 

Is there any public documentation outlining the changes that are implemented in this repo? If not, have you considered adding a `CHANGELOG` file?

I think it would really help out developers implementing AppSync to be made aware of some of the recent changes that are being added.

Thanks!

**Comment by manueliglesias** [comment]
Hi @jessedoyle 

There is a CHANGELOG file per package (this is a monorepo):

https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/master/packages/aws-appsync/CHANGELOG.md

Thanks for using this package!

**Comment by jessedoyle** [comment]
@manueliglesias - Oops - sorry that was my mistake! I guess I just didn't look far enough 👍
