### ISSUE TITLE
SSR Vue.js window polyfill

### ISSUE THREAD

**Issue by iskanderbroere** [awslabs/aws-mobile-appsync-sdk-js#180]
Vue-router checks whether it is in the browser or not like this.
```js
var inBrowser = typeof window !== 'undefined';
```
https://github.com/vuejs/vue-router/blob/d50cb20d9541e69caf746f03845ef585bbece099/dist/vue-router.common.js#L572

The first issue occurs in where the router can't find the user-agent in the polyfilled window:
https://github.com/vuejs/vue-router/blob/d50cb20d9541e69caf746f03845ef585bbece099/dist/vue-router.common.js#L1660

I think it would be nice if we could pass a boolean to the appsyncclient whether we are in the browser or on the server, rather than polyfill the window.

If this is not possible it would be nice if you'd make the polyfill compatible with vue ssr.

This issue is reproducable with nuxt starter template and the vue setup from the aws tutorials.

I could provide a more detailed reproduction if this is not enough. Thanks for reading.

**Comment by elorzafe** [comment]
Hi @iskanderbroere, thanks for your feedback!. 

I will mark this as a feature request

**Comment by manueliglesias** [comment]
Hi @iskanderbroere 

I think this SDK is no longer *polyfilling* the window object:

https://github.com/awslabs/aws-mobile-appsync-sdk-js/search?q=window&unscoped_q=window

Are you still having this issue with the latest version? Feel free to re-open if that's the case
