### ISSUE TITLE
AppSync, S3 and React Native (Expo)

### ISSUE THREAD

**Issue by mlecoq** [awslabs/aws-mobile-appsync-sdk-js#183]
Hi,

I do not succeed in uploading pictures on s3 on my react native app (see [https://stackoverflow.com/questions/51366876/aws-appsync-cognito-s3](https://stackoverflow.com/questions/51366876/aws-appsync-cognito-s3))

I have tried many ways to put params for localUri ( {fileName, mimeType} like in https://github.com/aws-samples/aws-amplify-graphql, base64, file uri ...). There is no information in appsync logs to explain why file is not uploaded to s3 (whereas an entry is added in dynamodb table). Looking in redux inspector, I see commit_offline_mutation actions like if everything worked fine. File upload silently fails. 

sdk should warn us when file upload is not possible. 

It could help us to figure out which mistake has been made.

**Comment by mlecoq** [comment]
I have succeeded in uploading my file, but associated dynamodb is not created

**Comment by mlecoq** [comment]
In fact here is my schema


```
input PictureInput {
  ede_number: String!
  file: S3ObjectInput!
}

enum Visibility {
  public
  private
}

type S3Object {
  bucket: String!
  region: String!
  key: String!
}

input S3ObjectInput {
  bucket: String!
  region: String!
  localUri: String
  visibility: Visibility
  key: String
  mimeType: String
}

type Picture {
  picture_id: String!
  ede_number: String!
  file: S3Object
}
```

So I have a picture object with a file sub-object
in complex-object-link there is this code 

```
  uploadPromise = Promise.resolve(uploadCredentials).then(credentials => upload(fileField, { credentials }).then(() => {
                    const { bucket, key, region } = fileField;
                    operation.variables[fileFieldKey] = { bucket, key, region };

                    return operation;
                }).catch(err => {
                    const error = new GraphQLError(err.message);
                    error.errorType = 'AWSAppSyncClient:S3UploadException'

                    throw new ApolloError({
                        graphQLErrors: [error],
                    });
                }));
```


which causes the following error:

"GraphQL error: The variables input contains a field name 'bucket' that is not defined for input object type 'PictureInput' "

because fileFieldKey is picture and it replaces picture with  { bucket, key, region } (instead of file)

**Comment by mlecoq** [comment]
There is a solution by splitting Picture and S3Object and having 2 variables in mutation instead of one. 

My current mutation is : 

` addPicture(picture: PictureInput!): Picture`

changing it in 

 `addPicture(file: S3ObjectInput!, ede_number: String!): Picture` will solve my case. Anyway, I think the sdk should support file sub objects. If you agree, I could make a PR.

**Comment by mlecoq** [comment]
Pull request made : #204

**Comment by mlecoq** [comment]
In your schema, you have to define one of your mutation variables as {key, bucket, region}.

On client side, you have to send this variable as {localUri, mimeType, key, bucket, region} : appsync sdk will use localUri and mimeType to upload the file to s3 bucket (and then will only send key, bucket and region infos to appsync endpoint)

**Comment by serendipity1004** [comment]
@mlabieniec I really feel like I'm going crazy now. It would be great if you can be kind enough to take a look at this just one more time.

I have my inputs looking like below
```
let post = {
    title: 'title',
    creator: 'Ji Ho',
    content: 'content'
}

let images = {
    bucket:'bucket-name'
    key:'key' - I auto id this in resovler
    region : 'ap-northeast-1'
    mimeType:'image/jpeg'
}
```

I have a resolver that looks like below on createPost

```
## Recreate input object
#set($post = {})
#set($postInput = $ctx.args.post)

$util.qr($post.put("title", $postInput.title))
$util.qr($post.put("content", $postInput.content))
$util.qr($post.put("type", $postInput.type))
$util.qr($post.put("creator", $ctx.identity.username))
$util.qr($post.put("createdAt", $util.time.nowISO8601()))
$util.qr($post.put("like", 0))
$util.qr($post.put("dislike", 0))
$util.qr($post.put("frozen", false))

## Recreate S3Object
#set($imagesArr = [])
#foreach($image in $ctx.args.images)
	$util.qr($imagesArr.add($util.dynamodb.toS3Object($util.autoId(), "bucket", "region", "0")))
#end
$util.qr($post.put("images", $imagesArr))

{
    "version" : "2017-02-28",
    "operation" : "PutItem",
    "key" : {
        "id": $util.dynamodb.toDynamoDBJson($util.autoId()),
    },
    "attributeValues" : $util.dynamodb.toMapValuesJson($post)
}
```

I get this list inserted to my images column

```
[  { "M" : {      "S" : { "S" : "{\"s3\":{\"key\":\"key\",\"bucket\":\"bucket\",\"region\":\"region\",\"version\":\"0\"}}" }    }  }]
```

The 'bucket', 'region' are correctly set to my bucket name and my bucket region of course.

I think the only difference with your input and mine is whether the images are in array or a single object. If you have any suggestions to what might be going wrong, please tell me. Thank you very much!

**Comment by mlecoq** [comment]
Array are not supported. In fact the sdk check if one of your mutation variables has the format {key, bucket ...} to upload files. So array are not viewed

**Comment by mlecoq** [comment]
See #161

**Comment by serendipity1004** [comment]
@mlecoq it is unbelievably still not working... document is created just fine with S3Object but no upload... I have no single idea why

**Comment by mlecoq** [comment]
Put some logs in complex-object-link.js in node-modules/AWS-appsync/lib directory, especially in catch blocs to see which errors are raised

**Comment by manueliglesias** [comment]
Hi @serendipity1004 

As @mlecoq correctly pointed out, the SDK only uploads the file to S3 if **all 5 keys are present**: 
>On client side, you have to send this variable as {localUri, mimeType, key, bucket, region} : appsync sdk will use localUri and mimeType to upload the file to s3 bucket (and then will only send key, bucket and region infos to appsync endpoint)

`{localUri, mimeType, key, bucket, region}`.  These keys are all needed to call S3. `localUri` can be anything the S3 client accepts:
```
Body — (Buffer, Typed Array, Blob, String, ReadableStream)
```

I am working on adding unit tests for this logic (so you can see clearly what is expected in terms of variables), I'll reference this issue in the PR once ready.

That same PR will probably add support for arrays (#161)

**Comment by dhiraj-belkhode** [comment]
@manueliglesias please have a look into #179

**Comment by motae99** [comment]
providing all above still doesn't work, entry is created but file is not uploaded

**Comment by mikeRChambers610** [comment]
Hi @mlecoq - it seems you have got the S3Object uploading successfully through the AppSync resolver to S3 and automatically storing the url as an item in the DynamoDB table? 

If so, I would really appreciate it if you could share your code with us. I am looking for an example of the react native client side uploading (my upload has an undefinded mimeType. Is this expected?).

I see the mutation you are using, could you share your resolver? Also, is your S3 bucket public? I can not figure out how to authorize the cognito user other than using the docs ( complexObjectsCredentials: () => Auth.currentCredentials(),).

Thanks in advance!!

**Comment by mlecoq** [comment]
@mikeRChambers610 

S3 bucket is not public, in fact I had to use federated identities (cognito only is not sufficient) to associate a role with grant access to bucket. The resolver : 

On appsync I does not receive the file but an object (with bucket, region and key):

```
type File {
  bucket: String!
  region: String!
  key: String!
}

input PictureInput {
  bucket: String!
  region: String!
  key: String!
}

type Picture {
  picture_id: String!
  file: File
}


type Mutation {
  addPicture(picture: PictureInput!): Picture
}
```

**Comment by mikechambers610** [comment]
@mlecoq @motae99 Thank you for the responses. I appreciate all of the help that I can get. My react native app is using cognito user pools and has been working fine. For testing purposes my S3 bucket is public. Would you please review my configuration below and let me know where I might be going wrong? Thanks a lot!

REACT NATIVE METHOD (No error but nothing happens on the backend) --

sendPicS3 = async () => {

   let file;
   let uri = this.state.result;

     if (uri) { // selectedFile is the file to be uploaded, typically comes from an <input type="file" />
       const { name, type: mimeType } = uri;
       const [, , , extension] = /([^.]+)(\.(\w+))?$/.exec(name);

       const bucket = AWSConfig.aws_content_delivery_bucket;
       const region = AWSConfig.aws_content_delivery_bucket_region;
       const key = [uuidV4(), extension].filter(x => !!x).join('.');

       file = {
         bucket,
         key,
         region,
         mimeType,
         localUri: uri,
       };

       console.log(file)

       this.props.onCreateTestFile({
         username: this.state.username,
         file: file,
       })

 }
}


REACT NATIVE GRAPHQL MUTATION --

import graphql from 'graphql-tag'

export default graphql`
mutation CreateTestFile ($username: String!, $file: S3ObjectInput!){
  createTestFile(
    input:
     {username: $username, file: $file}
  )
  {
    username
    file
  }
}
  `

APPSYNC SCHEMA 


input CreateTestFileInput {
	username: String!
	file: S3ObjectInput!
}

type S3Object {
	bucket: String!
	region: String!
	key: String!
}

input S3ObjectInput {
	bucket: String!
	region: String!
	localUri: String
	visibility: Visibility
	key: String
	mimeType: String
}

APPSYNC MUTATION 

createTestFile(username: String!, file: S3ObjectInput!): TestFile



APPSYNC RESOLVER

{
    "version": "2017-02-28",
    "operation": "PutItem",
    "key": {
        "id": $util.dynamodb.toDynamoDBJson($ctx.args.input.username),
    },

    #set( $attribs = $util.dynamodb.toMapValues($ctx.args.input) )
    #set( $file = $ctx.args.input.file )
    #set( $attribs.file = $util.dynamodb.toS3Object($file.key, $file.bucket, $file.region) )

    "attributeValues": $util.toJson($attribs)
}

APPSYNC RESPONSE RESOLVER

## Request Resolver ##
{
    "version": "2017-02-28",
    "payload": {}
}

## Response Resolver ##
$util.toJson($util.dynamodb.fromS3ObjectJson($context.source.file))

**Comment by motae99** [comment]
Something prevents file from upload using the SDK which accept blob type u
haven't shared this code which is most likely the reason, after file is
selected by the user u need to process it and convert it to blob if not by
default it all depends on the extension u using for file upload
I'll share my code with ya, it works just fine

**Comment by mikechambers610** [comment]
Thanks @motae99 I would appreciate if you could share your code that would help me a lot. 
I am kind of new to the file transfer aspect and using AppSync is just throwing me through a loop.

**Comment by mikechambers610** [comment]
@motae99 I am using the ImagePicker and storing the uri for the image selected in this.state.result.
After that I am storing this.state.result as "uri" and passing that directly. I think that is probably the wrong way as you as saying it seems like I need to be converting the file just not sure how to do that. Thanks!!

**Comment by motae99** [comment]
You need to pass your uri to .blob() to convert to blob data, like below
code
otherwise there are some extensions that do that for you automatically
if (selectedFile) {
const { fileName: fileName, type: mimeType } = selectedFile;
const [, , , extension] = /([^.]+)(\.(\w+))?$/.exec(fileName);

const key = `${visibility}/${identityId}/${uuid()}${extension && '.'}${
extension}`;

const imageData = await fetch(selectedFile.uri)
const blobData = await imageData.blob()

file = {
bucket,
key,
region,
mimeType,
localUri: blobData,
};
}

**Comment by mikeRChambers610** [comment]
Thank you @motae99 . Do I need to import npm i react-native-fetch-blob ? Or is this .blob() a part of the JS and no imports needed for it?

**Comment by motae99** [comment]
No you don't need 2

**Comment by mikechambers610** [comment]
@motae99 Hi - I have one more small question. In React Native Image Picker there is no fileName available in the picture object. Is there a work around for this in RN?

**Comment by mikechambers610** [comment]
This is what I am seeing when pulling from the image picker result : {cancelled: false, width: 1125, height: 750, uri: "file:///Users/mikechambers/Library/Developer/CoreS…gePicker/08E96CAF-64AC-4643-BEE1-3715F66A9938.jpg", type: "image"}
cancelled: false
height: 750
type: "image"
uri: "file:///Users/mikechambers/Library/Developer/CoreSimulator/Devices/40324C37-2355-4F94-B186-0F27B92B469B/data/Containers/Data/Application/889A8A54214-B4D1-494DF88C3047/Library/Caches/ExponentExperienceData/%2540anonymous%252Fnavigationlayout-3c2170ba-98a6-46aa-bdef-ab310810b31c/ImagePicker/086CAF-64AC-4EE1-3715F66A9938.jpg"
width: 1125
__proto__: Object

**Comment by mikechambers610** [comment]
Thanks @motae99 & @mlecoq . I have created https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/335

I am not sure what is missing from my project but have had no luck with getting my S3Object working through Appsync from React-Native.

**Comment by motae99** [comment]
Hey U really don't need fileName to get it working only used to generate
meaningful key but u can just generate random unique key, it'd suffice,
* Generate ur key
* Make sure u have a mimetype
* Region and bucket of course
* Ur localuri in supported format in our case blob

If u ain't sure where does ur code break, I suggest u hardcoded on query
itself 2 confirm the desirable resault, then follow ur logs
Sharing ur error would help a lot
Leaving debug on for more insights
That's all I can say man hope it helps

**Comment by motae99** [comment]
In the code u shared ur mimetype is just type, stating the obvious

**Comment by mikechambers610** [comment]
Hi - I was able to acheive my goal of uploading a picture to S3 and having a url to the S3 object in my dynamoDB. First I am sending the file to S3 via the NPM package 'react-native-aws3'. Once the file is uploaded to the bucket which I have used IAM to grant the cognito role permission, the url is returned as a promise. I then fire off a mutation to dynamodb to create an item in the table with the pic attribute as a String where I am storing the URL. Below code is working :

sendPicS3 = async () => {

```
 //console.log(this.state.result)
 let file = {
 // `uri` can also be a file system path (i.e. file://)
 uri: this.state.result.uri,
 name: uuidV4()+"profpic.jpg",
 type: "image/png"
}

const config = {
  keyPrefix: "profPic/",
  bucket: AWSConfig.aws_resource_bucket_name,
  region: AWSConfig.aws_project_region,
  accessKey: AWSKeys.acckey,
  secretKey: AWSKeys.seckey,
  successActionStatus:201
}
console.log(config)

RNS3.put(file, config).then(response => {
```
if (response.status !== 201) {
throw new Error("Failed to upload image to S3");
} else{

```
console.log(response)
  let id = this.state.backupusername
  //below is the url in the response from the S3 upload
  let profPic = response.body.postResponse.location


 this.props.onUpdateMember({
    id: id,
    profPic: profPic,
  })

  this.setState({
    result: '',
    cancelled: "true",
    profPicChange: "false"
  })
```
}
});

}

**Comment by jtaylor1989** [comment]
I struggled a lot in implementing file upload using Amplify, AppSync, and S3. Now reading all your answers and working on my own I thought it will be great to share my own solution.

I am using [Expo](https://docs.expo.io/versions/v28.0.0/sdk/camera/#__next) to access the library of the device, RNS3 to put the image in S3, and the [AppSync SDK](https://aws-amplify.github.io/docs/js/api#aws-appsync-sdk) to execute the mutation that store the reference in DynamoDB.

Here are screenshots of my entire code. Keys are from your IAM user.

schema.graphql
<img width="667" alt="schema" src="https://user-images.githubusercontent.com/26605247/54024840-b76d4b00-4190-11e9-8a66-5d8f65c66a52.png">

MutationCreatePicture.js
<img width="476" alt="mutation" src="https://user-images.githubusercontent.com/26605247/54024839-b76d4b00-4190-11e9-8e14-d9397acc370c.png">

App.js
<img width="666" alt="app" src="https://user-images.githubusercontent.com/26605247/54024836-b76d4b00-4190-11e9-8d07-ff2d9448acb0.png">

First half of the AddPhoto.js
<img width="669" alt="addphoto-1" src="https://user-images.githubusercontent.com/26605247/54024834-b6d4b480-4190-11e9-9c09-5f5892ee7b4e.png">

Second half of the AddPhoto.js
<img width="669" alt="addphoto-2" src="https://user-images.githubusercontent.com/26605247/54024835-b76d4b00-4190-11e9-8a50-4d235c0fee58.png">

keys.js
<img width="670" alt="keys" src="https://user-images.githubusercontent.com/26605247/54024837-b76d4b00-4190-11e9-800a-9c435db3b606.png">

I tried getting rid of RNS3 by using the [Storage](https://aws-amplify.github.io/docs/js/storage) API to put the image in S3 (going fully Amplify), but the uploaded image is always broken.

**Comment by isocra** [comment]
I'm trying to do a similar thing with Expo and react native and can't get the upload to S3 working correctly. I'm storing the photos in a `photos` subdirectory, so my local url is given by 
```typescript
  const imageUri = `${FileSystem.documentDirectory}/photos/${filename}`;
```
Then exactly as described above, I've got
```typescript
  const imageData = await fetch(imageUri);
  const blobData = await imageData.blob();
  const variables = {
    key: filename,
    region: 'eu-west-2',
    bucket: BUCKET_NAME,
    mimeType: 'image/jpeg',
    localUri: blobData
  }
```
And that's then passed to the mutation.

Following its path through the debugger, it goes all the way through to the call in node_modules/aws-appsync/lib/link/complex-object-link-uploader.native.js line 19. Here the Body is of this form:
```javascript
{
  _data: {
    blobId: "5deabc19-2d0e-42f1-9e3c-1667f5a56e7e", 
    offset: 0, 
    size: 0, 
    type: "", 
    lastModified: 1552561833865
  }
}
```
What's surprising is if I test `blobData instanceof Blob` up at the beginning, it returns true, but when I try `Body instanceof Blob` down in complex-object-link-uploader.native.js, then it returns false!!

It feels like my very close, but I just can't see how to make it work... I've tried other approaches like turning it into base64 and putting the string in to localUri, but then the file stored in S3 simply has the base64 encoded version of the image, it doesn't decode it back to an image. 

What am I doing wrong?

**Comment by jtaylor1989** [comment]
> I'm trying to do a similar thing with Expo and react native and can't get the upload to S3 working correctly. I'm storing the photos in a `photos` subdirectory, so my local url is given by
> 
> ```ts
>   const imageUri = `${FileSystem.documentDirectory}/photos/${filename}`;
> ```
> 
> Then exactly as described above, I've got
> 
> ```ts
>   const imageData = await fetch(imageUri);
>   const blobData = await imageData.blob();
>   const variables = {
>     key: filename,
>     region: 'eu-west-2',
>     bucket: BUCKET_NAME,
>     mimeType: 'image/jpeg',
>     localUri: blobData
>   }
> ```
> 
> And that's then passed to the mutation.
> 
> Following its path through the debugger, it goes all the way through to the call in node_modules/aws-appsync/lib/link/complex-object-link-uploader.native.js line 19. Here the Body is of this form:
> 
> ```js
> {
>   _data: {
>     blobId: "5deabc19-2d0e-42f1-9e3c-1667f5a56e7e", 
>     offset: 0, 
>     size: 0, 
>     type: "", 
>     lastModified: 1552561833865
>   }
> }
> ```
> 
> What's surprising is if I test `blobData instanceof Blob` up at the beginning, it returns true, but when I try `Body instanceof Blob` down in complex-object-link-uploader.native.js, then it returns false!!
> 
> It feels like my very close, but I just can't see how to make it work... I've tried other approaches like turning it into base64 and putting the string in to localUri, but then the file stored in S3 simply has the base64 encoded version of the image, it doesn't decode it back to an image.
> 
> What am I doing wrong?

Check this component in my repo in [here](https://github.com/jtaylor1989/react-native-s3/blob/master/components/ImageUploadS3.js). I use Amplify Storage API to put and get images from S3.

**Comment by isocra** [comment]
Hi @jtaylor1989,

Thanks for the link. I tried putting your code into my project and it saves zero-length files, whereas if I run your code exactly as-is, yours works fine. So I _think_ that maybe I'm importing something that is messing stuff up? Or I'm not including something I need? I notice, for example, that you've got `rn-fetch-blob` in your package.json. That seems to have polyfills for fetch and Blob, but you're not actually using them? I tried just adding them to my project but it didn't make any difference. You're also using expo 30 whereas I'm using 32. Any pointers on where I should look?

**Comment by isocra** [comment]
I finally found the problem: for some reason in Expo:32, using `fetch()` and then `.blob()` doesn't return you the proper object with all the data (no size and no type).

Luckily, @yonahforst posted a solution here: https://github.com/expo/firebase-storage-upload-example/issues/13#issuecomment-437597679

Basically I needed to get the blob in a different way, here's my version:
```typescript
const urlToBlob = (url: string) => {
  return new Promise((resolve, reject) => {
    var xhr = new XMLHttpRequest();
    xhr.onerror = reject;
    xhr.onreadystatechange = () => {
      if (xhr.readyState === 4) {
        resolve(xhr.response);
      }
    };
    xhr.open('GET', url);
    xhr.responseType = 'blob'; // convert type
    xhr.send();
  });
};
```
Then my example above becomes: 
```typescript
  const blobData = await urlToBlob(imageUri);
  const variables = {
    key: filename,
    region: 'eu-west-2',
    bucket: BUCKET_NAME,
    mimeType: 'image/jpeg',
    localUri: blobData
  }
```
With that in place, the upload happens successfully and then the mutation works too. 

If anyone is wondering why their file isn't uploading, I recommend putting a breakpoint on line 60 or so of `node_modules/aws-appsync/lib/link/complex-object-link.js`. This is basically where the observer checks to see whether an upload is needed and if it has all the data it needs.

Thanks again @jtaylor1989 for giving me the clue I needed :-)
