### ISSUE TITLE
apmlify + appsync subscriptions stop getting data after some time

### ISSUE THREAD

**Issue by praveshkhatana** [awslabs/aws-mobile-appsync-sdk-js#190]
Do you want to request a feature or report a bug?
bug
What is the current behavior?
subscriptions initially work but timeout after a while and no data is then received on the client.

What is the expected behavior?
subscriptions not timing out automatically. Or if timeout is a feature, then the ability to manually specify timeout/ disable timeout.

Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
same across different versions

```
CONSOLE LOG [native code]: {
"[INFO] 24:12.893 MqttOverWSProvider": {
"errorCode": 8,
"errorMessage": "AMQJS0008I Socket closed.",
"uri": "wss://<uri>
```

**Comment by Negan1911** [comment]
Same issue here, looks like the socket got closed, but by #132 i'm not able to get an error to resubscribe when that happens, i don't know how to proceed and it's blocking me to release my app with this technology

**Comment by praveshkhatana** [comment]
It's fixed in new version, now i can resubscribe to topics again after getting socket close error. :blush:

**Comment by jp928** [comment]
@praveshkhatana 
Do you mind to share how do you detect the error?

**Comment by praveshkhatana** [comment]
@jp928 I am using NativeScript+Angular.

aws version
```
"aws-amplify": "^1.1.13",
    "aws-appsync": "^1.7.0",
```

here is the code
```
async onUpdateApplicationSubscription() {
    let applicationSubscription: any = await this._subscription.onUpdateApplication();
    this.applicationSubscription = await applicationSubscription.subscribe({
      next: data => {
        this.applicationUpdateHandler(data.value.data);
      },
      error: err => {
       this.applicationSubscription.unsubscribe(); //just for safe side
        this.onUpdateApplicationSubscription();
      }
    });
    return;
  }
```
