### ISSUE TITLE
Mutation request that ends in Validation Error doesn't float error message to Promise's catch handler.

### ISSUE THREAD

**Issue by LukeMizuhashi** [awslabs/aws-mobile-appsync-sdk-js#196]
I have the following client code running in the browser:

```JavaScript
client.hydrated().then(function handleClientHydrated(client) {
      client.mutate({
        mutation: createStuff,
        variables: {
          listOfStuff: listOfStuff,
        },
      }).then(function handleMutationSuccess(data) {
        console.log(arguments);
        if (!data.listOfStuff) {
          throw new Error(`Server returned 200, but there was a validation error--and I can't see the error passed from the server via npm's require('aws-appsync').default module`);
        }
      }).catch(function handleMutationFailure() { // This never gets called.
        console.error('failure',arguments);
      });
    });
```

In the network pane, it looks like AWS AppSync returns Status Code 200 and a nice object with juicy error information.

Should that error information be passed to the success callback? How about the error callback? Should the error callback get called?

**Comment by LukeMizuhashi** [comment]
Personally, I would think the error handler should get called: as a user of the node module's public interface, when I call `mutate()` I expect something to get mutated on the database. If that doesn't happen, I want to know why and handle app state via the `Promise.catch()` callback.

That being said--I've not read any of the specs that the node module needs to be constrained by. So--my expectations might be outside spec. I don't know.

**Comment by ArronHsiao** [comment]
I can use mutate function to successfully create new table, but can't receive result back, something like

  client.mutate({ mutation: mutations.createUser, variables: { .... } })
    .then(function logData(data) { console.log('results of mutation: ', data.data); }

just got 

results of mutation:  { createUser: null }

but the table creation is success

**Comment by Knowledge91** [comment]
My mutations also return null? What is the reason for this?

**Comment by raducretu** [comment]
+1 @ArronHsiao @Knowledge91

**Comment by elorzafe** [comment]
We have fixed this on the latest release (aws-appsync@1.4.0) I will close the issue for now, but feel free to create a new issue if this problem persist.
