### ISSUE TITLE
InMemoryCache does not have the correct type for AWSAppSyncClient

### ISSUE THREAD

**Issue by mikesol** [awslabs/aws-mobile-appsync-sdk-js#197]
The code below...
```
    const cache = new InMemoryCache();

    const link = withClientState({
      defaults: {
        foo: 'bar',
      },
      resolvers: {},
      cache
    });
    new AWSAppSyncClient({
      url: config.aws_appsync_graphqlEndpoint,
      region: config.aws_appsync_region,
      auth: {
          type: AUTH_TYPE.AWS_IAM,
          credentials: () => Auth.currentCredentials(),
      },
    }, {
      cache,
      link
    });
```
produces the following typescript error...
```Argument of type '{ cache: InMemoryCache; link: { writeDefaults(): void; request(operation: Operation, forward?: Ne...' is not assignable to parameter of type 'ApolloClientOptions<InMemoryCache> | undefined'.
  Type '{ cache: InMemoryCache; link: { writeDefaults(): void; request(operation: Operation, forward?: Ne...' is not assignable to type 'ApolloClientOptions<InMemoryCache>'.
    Types of property 'cache' are incompatible.
      Type 'InMemoryCache' is not assignable to type 'ApolloCache<InMemoryCache>'.
        Types of property 'restore' are incompatible.
          Type '(data: NormalizedCacheObject) => InMemoryCache' is not assignable to type '(serializedState: InMemoryCache) => ApolloCache<InMemoryCache>'.
            Types of parameters 'data' and 'serializedState' are incompatible.
              Type 'InMemoryCache' is not assignable to type 'NormalizedCacheObject'.
                Index signature is missing in type 'InMemoryCache'.
(property) cache: InMemoryCache
```

with these packages...

```
    "apollo-cache-inmemory": "^1.2.6",
    "apollo-client": "^2.3.7",
    "apollo-link": "^1.2.2",
    "apollo-link-state": "^0.4.1",
    "aws-amplify": "^1.0.2",
    "aws-amplify-react": "^1.0.2",
    "aws-amplify-react-native": "^1.0.2",
    "aws-appsync": "^1.3.2"
```

My guess is that it's a problem with how AWSAppSyncClient does generics for the second optional object, but I'm not sure.  Any pointers/work-arounds would be appreciated!

**Comment by dhiraj-belkhode** [comment]
@mikesol  you should try this

import { ApolloLink } from 'apollo-link';
import { withClientState } from 'apollo-link-state';
import AWSAppSyncClient, { createAppSyncLink, createLinkWithCache } from "aws-appsync";

const stateLink = createLinkWithCache(cache => withClientState({
  cache,
  resolvers: {},
}));

const awsAppSyncLink = createAppSyncLink({
      url: config.aws_appsync_graphqlEndpoint,
      region: config.aws_appsync_region,
      auth: {
          type: AUTH_TYPE.AWS_IAM,
          credentials: () => Auth.currentCredentials(),
      }
});

const link = ApolloLink.from([stateLink, appSyncLink]);
const client = new AWSAppSyncClient({}, { link });

**Comment by builtbyproxy** [comment]
Works great except for the second last line which I imagine should be: 
`const link = ApolloLink.from([stateLink, awsAppSyncLink]);`

**Comment by elorzafe** [comment]
@mikesol are you still having this issue?

**Comment by elorzafe** [comment]
I will close this for now, but feel free @mikesol to reopen this issue or to create a new one.
