### ISSUE TITLE
AppSync AWS Defined Scalars throw error "not found in document"

### ISSUE THREAD

**Issue by devautor** [awslabs/aws-mobile-appsync-sdk-js#199]
Appsync schema editor complains about using AWS defined scalras, i.e. AWSEmail, AWSDate, etc. with the error shown as:
`Type "AWSDate" not found in document.`

Is it to be used differently than other scalars? Docs don't seem to imply so!

**Comment by elorzafe** [comment]
Hi @devautor, I have just tried this on AppSync console and is not a problem anymore. Please feel free to create another issue related to the AppSync service related. [on the official AWS AppSync forum](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0)

For AppSyncClient issues feel free to create on this repo.


Thanks,
Francisco
