### ISSUE TITLE
Rehydrated should not return <div className> and use something like render(child) prop instead

### ISSUE THREAD

**Issue by pronevich** [awslabs/aws-mobile-appsync-sdk-js#2]
Now [Rehydrate in Rehydrated](https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/87c52f48af957f21d335d1e53111d68479b41e38/packages/aws-appsync-react/src/rehydrated.tsx#L20) return div element, what user doesn't expect, because purpose of `Rehydrated` not layout/styles, but data hydration, same as ApolloProvider doesn't insert any markup. As result `Rehydrated` breaks layout. This is of course could be fixed by adding styles to 'awsappsync', but this not what lib user wish I think.

Second issue is fixed  `<span>Loading...</span>` that also breaks layout and can't be customized.

Solution can be simple and known as [render prop](https://cdb.reacttraining.com/use-a-render-prop-50de598f11ce) . `Rehydrated` can take render prop or child `({isRehydrated}) => isRehydrated ? <App/> : <CustomLoading/>`

**Comment by manueliglesias** [comment]
Thanks @pronevich , This will be fixed by your PR #6
