### ISSUE TITLE
Better example for handling complex objects

### ISSUE THREAD

**Issue by sid88in** [awslabs/aws-mobile-appsync-sdk-js#20]
Hey 

I am trying to understand how to use complex objects as described [here](https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-react.html). 

Is there a better example to show how to write mapping templates for complex objects? For instance, let's say user profile info (picture, video etc) is stored in S3 bucket and I want to Query that info using GraphQL endpoint, how would I do that.

thanks
Sid

**Comment by firstplacelabs** [comment]
I am also trying to find an example on how to upload complex objects to s3. To further complicate things, I am trying to use aws-amplify. Amplify has it's own Storage feature providing public/private uploads to an s3 bucket. Does aws-appsync plan to integrate with this feature?

Also is it possible to pass Amplify's essentialCredentials for accessKeyId and secretAccessKey in the AWSAppSyncClient config? This seems to fit the requirements for complexObjectsCredentials.
Reference: https://github.com/aws/aws-amplify/blob/master/packages/aws-amplify/src/Auth/Auth.ts

**Comment by sid88in** [comment]
I think this is addressed by new documentation!

Thanks
Sid

**Comment by undefobj** [comment]
We have also released a sample application for this: https://github.com/aws-samples/aws-amplify-graphql

**Comment by sid88in** [comment]
looks great! thanks!

**Comment by M1chaelTran** [comment]
Is there an example for multiple files upload?

I can't seem to be able to get it working with multiple files.

thank you in advance

**Comment by getsbydev** [comment]
Do I have to strictly specify the "complexObjectsCredentials" in the AppSyncClient? I'm using an android client with cognito authentication and tried to upload a complex object to s3. The mutation works, but my bucket is still empty and no exceptions are thrown.

Any ideas?
