### ISSUE TITLE
Calling Object.keys() on null object throws an error

### ISSUE THREAD

**Issue by onlybakam** [awslabs/aws-mobile-appsync-sdk-js#210]
https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/cc07b7997c2d616806f1a0e9f3e90e76e05e3b79/packages/aws-appsync/src/helpers/offline.ts#L185

when dealing with connections, backend could return:

```javascript
{
items: [...],
nextToken: null
}
```
and  `typeof null === 'object'`, 

Iterating through keys, can come across null values. calling Object.keys(null) throws an error

recommend doing:

```javascript
if (typeof obj !== 'object' || obect === null || object === undefined) {
    return undefined;
}
```

also see: [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof#null)

**Comment by manueliglesias** [comment]
Closed by #211
