### ISSUE TITLE
Time traveling and undo/redo

### ISSUE THREAD

**Issue by dennari** [awslabs/aws-mobile-appsync-sdk-js#214]
Since the AppSync client records the mutations in offline mode and is able to revert them, i.e. travel back in time, when coming back online I would imagine the machinery for undo/redo is almost in place. Is this something that could be supported?

**Comment by elorzafe** [comment]
@dennari Undo/redo is not supported on offline mode. Mutations are enqueued so when you go back online it started to send to those to the server. In what graphql scenario would you do undo/redo this?

**Comment by elorzafe** [comment]
I will close this for now, but feel free @dennari to reopen this issue or to create a new one.
