### ISSUE TITLE
Mapping template for self referencing object

### ISSUE THREAD

**Issue by sid88in** [awslabs/aws-mobile-appsync-sdk-js#22]
Schema:

```
type Query {
	getUserTwitterFeed(handle: String!): User!
}

type Tweet {
	tweet_id: String!
	tweet: String!
	retweeted: Boolean!
	retweet_count: Int
	favorited: Boolean!
	created_at: String!
}

type TweetConnection {
	items: [Tweet!]!
	nextToken: String
}

type User {
	name: String!
	handle: String!
	followers: [User]
	tweets(limit: Int, nextToken: String, keyword: String): TweetConnection
}

schema {
	query: Query
}
```

Data Source:
```
Hashkey = handle
sortKey = tweet_id
attributes : name, tweet, tweet_id, retweeted.. 
```

I have a mapping template associated with User and tweet given below

User: 
```
{
    "version" : "2017-02-28",
    "operation" : "Query",
    "query" : {
        ## Provide a query expression. **
        "expression": "handle = :handle",
        "expressionValues" : {
            ":handle" : {
                "S" : "${context.arguments.handle}"
            }
        }
    }
}
```

tweets:

```
{
    "version": "2017-02-28",
    "operation": "Query",
    "query": {
        "expression": "handle = :handle",
        "expressionValues": {
            ":handle": {
                "S": "$context.source.handle"
            }
        }
    },
    "limit": #if($context.arguments.limit) $context.arguments.limit #else 10 #end,
    "nextToken": #if($context.arguments.nextToken) "$context.arguments.nextToken" #else null #end
    #if(${context.arguments.keyword})
    ,"filter": {
        "expression": "begins_with (#tweet, :keyword)",
        "expressionNames" : {
          	"#tweet" : "tweet"
        },
        "expressionValues": {
            ":keyword": { "S": "${context.arguments.keyword}" }
        }
      }
    #end
}
```
Note: the above filter expression is not working explained [here](https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/19) but for this particular question lets not worry about it.

Question:
How do I handle self-referencing User in followers: [User]. Each user can have a list of followers stored as string in the database attribute for example: followers : ["sid", "gupta"]

Now when we query dynamo via GraphQL we fetch data for a given handle but each handle/user can have multiple followers and we might want to get data for each follower as well. 

I am trying to look into Batch Get Item. Something like this:

```
{
    "RequestItems": {
        "users": {
            "Keys": [
                {
                    "handle":{"S":"sid"} -- $context.source.followers[0]
                },
                {
                    "Name":{"S":"gupta"} -- $context.source.followers[1]
                }
            ],
            "ProjectionExpression":"tweet, retweet_count"
        }
    },
    "ReturnConsumedCapacity": "TOTAL"
}
  ```
Is this kind of query supported by GraphQL? Not sure how to proceed here.

**Comment by sid88in** [comment]
<img width="531" alt="screen shot 2018-01-22 at 12 42 38 pm" src="https://user-images.githubusercontent.com/1587005/35243445-c3febf50-ff71-11e7-9c29-b84c0378bc81.png">

**Comment by mlshon** [comment]
Hi,

I'm assuming you're querying `getUserTwitterFeed`.  What is the request mapping template for that?  We currently don't support the DynamoDB's BatchGetItem.

**Comment by sid88in** [comment]
@mlshon thanks for getting back. Request mapping for getUserTwitterFeed is:

```{
    "version" : "2017-02-28",
    "operation" : "Query",
    "query" : {
        ## Provide a query expression. **
        "expression": "handle = :handle",
        "expressionValues" : {
            ":handle" : {
                "S" : "${context.arguments.handle}"
            }
        }
    }
}```

and for tweets is:

```
{
    "version": "2017-02-28",
    "operation": "Query",
    "query": {
        "expression": "handle = :handle",
        "expressionValues": {
            ":handle": {
                "S": "$context.source.handle"
            }
        }
    },
    "limit": #if($context.arguments.limit) $context.arguments.limit #else 10 #end,
    "nextToken": #if($context.arguments.nextToken) "$context.arguments.nextToken" #else null #end
    #if(${context.arguments.keyword})
    ,"filter": {
        "expression": "begins_with (#tweet, :keyword)",
        "expressionNames" : {
          	"#tweet" : "tweet"
        },
        "expressionValues": {
            ":keyword": { "S": "${context.arguments.keyword}" }
        }
      }
    #end
}
```

**Comment by sid88in** [comment]
I did talk to Michael and he told me the same.  One thing I still am trying to figure out is to use filtering in the mapping template with pagination : https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/19

Also not sure if there is another way to do self referencing without using batchgetitem (not that I am aware of) but will be waiting for your batchitem integrations :) 

thanks!

**Comment by mlshon** [comment]
Regarding filtering, I added a new comment to that thread. Basically, we have a fix out so you should retry the filtering!

**Comment by sid88in** [comment]
It worked :D:D thanks!!!
