### ISSUE TITLE
Bad TS types prevent setting of defaultOptions

### ISSUE THREAD

**Issue by ffxsam** [awslabs/aws-mobile-appsync-sdk-js#220]
I get a type error with this code:

```js
const client = new AWSAppSyncClient(
  {
    url: appSyncConfig.graphqlEndpoint,
    region: appSyncConfig.region,
    auth: {
      type: appSyncConfig.authenticationType,
      // credentials: () => Auth.currentCredentials(),
      apiKey: () => appSyncConfig.apiKey,
    },
  },
  {
    defaultOptions: {
      watchQuery: {
        fetchPolicy: 'cache-and-network',
      },
    },
  }
);
```

```
ERROR in /Volumes/SuperData/Sites/reelcrafter/rc-ts/src/bootstrap/apollo-setup.ts
17:3 Argument of type '{ defaultOptions: { watchQuery: { fetchPolicy: "cache-and-network"; }; }; }' is not assignable to parameter of type 'ApolloClientOptions<InMemoryCache>'.
  Property 'link' is missing in type '{ defaultOptions: { watchQuery: { fetchPolicy: "cache-and-network"; }; }; }'.
    15 |     },
    16 |   },
  > 17 |   {
       |   ^
    18 |     defaultOptions: {
    19 |       watchQuery: {
    20 |         fetchPolicy: 'cache-and-network',
```

`ApolloClientOptions` requires `link` and `cache` to be passed. We need a way to be able to set the global `fetchPolicy`.

This code functions properly, and sets the right fetch policy. It's just that the type used is probably not the best option. I'm looking into somehow creating a new interface based off of `ApolloClientOptions` that doesn't have `link` and `cache` in it.

@manueliglesias I'm open to other ideas as well.

**Comment by ffxsam** [comment]
@manueliglesias I'm open to other ideas, too.

**Comment by ffxsam** [comment]
Opened a PR.

**Comment by manueliglesias** [comment]
Thanks @ffxsam !

I was evaluating upgrading to a newer version of typescript that would allow us to do something like: (using `Partial`)

```typescript
    constructor({
        url,
        region,
        auth,
        conflictResolver,
        complexObjectsCredentials,
        cacheOptions = {},
        disableOffline = false
    }: AWSAppSyncClientOptions, options?: Partial<ApolloClientOptions<TCacheShape>>) {
      // ...
    }
```

What are your thoughts on this?

**Comment by ffxsam** [comment]
Hey Manuel!

Honestly, I suck at TypeScript. :sweat_smile: I only know what I piece together from other people, at least for more complex things I don't understand. I'm cool with whatever you and the team think is best, as long as it lets us specify options without needing `link` and `cache`.

**Comment by manueliglesias** [comment]
Cool! It would be great if you can try the code from #226

**Comment by ffxsam** [comment]
@manueliglesias Works great!
