### ISSUE TITLE
Disable persistence in a node environment?

### ISSUE THREAD

**Issue by rygo6** [awslabs/aws-mobile-appsync-sdk-js#227]
I am running in a node environment and am getting this.

```
redux-persist asyncLocalStorage requires a global localStorage object. Either use a different storage backend or if this is a universal redux application you probably should conditionally persist like so: https://gist.github.com/rt2zz/ac9eb396793f95ff3c3b
```

I have a index.js that is similar to the one shown here for Lambda:
https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-node.html

The error says just put this somewhere
`if (typeof self === 'object') persistStore(store)`

I can't figure out where to put that. How do I disable redux persistence in AppSync?

**Comment by manueliglesias** [comment]
Hi @rygo6 

You can try [disabling offline support](https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-reactnative.html#offline-settings):

```javascript
const client = new AWSAppSyncClient({
    url: AppSync.graphqlEndpoint,
    region: AppSync.region,
    auth: {
        type: AUTH_TYPE.API_KEY,
        apiKey: AppSync.apiKey,
    },
    disableOffline: true
});
```
