### ISSUE TITLE
Intermittent error retrieving data on a physical phone

### ISSUE THREAD

**Issue by russelltaga** [awslabs/aws-mobile-appsync-sdk-js#23]
Seeing a weird problem that should be easy to repro using the AppSync React starter app.

1) Create the AppSync API using the sample schema and API key auth
2) Download the AppSync.json file from the AppSync console
3) Clone the https://github.com/aws-samples/aws-mobile-appsync-events-starter-react repo
4) Drop in AppSync.json in the /src folder
5) npm install
6) Deploy to an S3 folder with a CloudFront distro. I'm doing this via the AWS CLI like so:
```
npm run build && aws s3 sync build/ s3://<BUCKET> && aws s3 cp --cache-control max-age=0 ./build/index.html s3://<BUCKET> && aws s3 cp --cache-control max-age=0 ./build/service-worker.js s3://<BUCKET>
```
7) On a computer, add a couple of events using the CloudFront URL. Refresh, clear browser cache, etc and things work like a charm.
8) On a physical phone try the same thing. You should intermittently see app crashes where no data will appear (no other clues on the console). I'm also able to repro via the XCode simulator in private browsing mode.

I posted this pull request with some updates to the AppSync client to get more clues via the Apollo Error Link.

https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/21

After those changes are in, I'm able to trigger the following error via a combination of browser refreshes and clearing the browser cache on the phone.
<img width="997" alt="screen shot 2018-01-22 at 8 01 18 pm" src="https://user-images.githubusercontent.com/27798268/35257878-c7bc66f8-ffb0-11e7-9ce9-f8a547556d36.png">

My guess is that this issue is related to what's described in this Apollo client bug.

https://github.com/apollographql/apollo-client/issues/1804

Specifically this statement caught my attention:

> If any of the data that readStore tries to read is not there, the function will throw an error

Forgive me as I'm still learning about how the local cache works, but my wild guess is since this is happening intermittently is that there's some kind of race condition where the local cache isn't initialized properly which results in an error being thrown.

Am more than happy to try to help, but would really appreciate any guidance or ideas on things to try.

**Comment by russelltaga** [comment]
I think this is a dup of https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/16

**Comment by russelltaga** [comment]
@manueliglesias After upgrading to aws-appsync 1.0.7 and disabling offline support, the app stops the crashing.

https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/33

Not certain if you want to keep this open or if there's more than I can potentially do to help root cause?

I saw that #16 was resolved, but not certain how to pull off that workaround in React.

**Comment by UnleashedMind** [comment]
close this issue for now, feel free to reopen if if it occurs again.
