### ISSUE TITLE
Websockets reconnection behaviour

### ISSUE THREAD

**Issue by yarax** [awslabs/aws-mobile-appsync-sdk-js#230]
Hi! I've just found out, that the library doesn't handle loosing of websocket connection (there is no apollo-error-link)
So using GraphQL subscriptions we don't have any possibility to handle reconnection.
Is it planned to support?

**Comment by jp928** [comment]
+ 1

**Comment by alez007** [comment]
This issue might be related to #132

**Comment by iudelsmann** [comment]
Hello, will there be any docs on how to use this?

**Comment by Negan1911** [comment]
@manueliglesias @elorzafe I see this merged but has not been released into npm, do we have an ETA about when this can land on npm?
