### ISSUE TITLE
Error when importing AWSAppSyncClient: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by ffxsam** [awslabs/aws-mobile-appsync-sdk-js#239]
I'm getting this error when simply importing the client:

`Uncaught ReferenceError: regeneratorRuntime is not defined`

```js
import AWSAppSyncClient from 'aws-appsync';
```

I can't give a repo because this is only occurring in a specific project and I can't share that code. Anyone have any ideas why this would be happening? It's in a Vue project. I Googled this error and it seems to mean that babel is not set up to use async/await, but that's not the case as I'm using it all over the place in my code.

**Comment by manueliglesias** [comment]
Hey @ffxsam 

Are you using babel? if so, can you try adding `babel-polyfill` or `babel-plugin-transform-runtime`?
([Seen here](https://stackoverflow.com/a/41331284/194974))

**Comment by ffxsam** [comment]
It's a Vue project (built with Vue CLI 3.0), which is strange because that usually includes everything needed. I believe polyfill is already in the project within Vue CLI's internals, since there's a `.browserslistrc` file in the project root.

My workaround was to add the `regenerator-runtime` package and then import it in `main.js`:

```js
import 'regenerator-runtime/runtime';
```

But this is the only project I'm having this issue in, so there must be something broken with the Vue build.
