### ISSUE TITLE
Backend Question: Access GraphQL Query At Resolver/Template Layer?

### ISSUE THREAD

**Issue by oxbits** [awslabs/aws-mobile-appsync-sdk-js#245]
Is it possible to access the GraphQL Query (Mutation/Subscription) submitted by the client at the Resolver/Template layer?  

It would be great if we could either pass it on to other GraphQL endpoints or see what is being requested.

**Comment by manueliglesias** [comment]
Hi @oxbits 

I am closing this issue in this repo in favor of the AWS Forums post since it is a service question.
