### ISSUE TITLE
Query with orderBy attribute 

### ISSUE THREAD

**Issue by wbeuil** [awslabs/aws-mobile-appsync-sdk-js#246]
I'd like to know if it's possible to implement an ascending/descending order filter to a Query schema ?

**Comment by manueliglesias** [comment]
Hi @wbeuil 

You can change the order by specifying [`ScanIndexForward`](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-ScanIndexForward):

> ScanIndexForward
> Specifies the order for index traversal: If true (default), the traversal is performed in ascending order; if false, the traversal is performed in descending order.

You can look at an example in the [AWS AppSync Resolver Mapping Template Reference for DynamoDB
](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-dynamodb.html#aws-appsync-resolver-mapping-template-reference-dynamodb-query)
