### ISSUE TITLE
No userPool

### ISSUE THREAD

**Issue by TJarriault** [awslabs/aws-mobile-appsync-sdk-js#249]
![capture](https://user-images.githubusercontent.com/7701382/45521762-b9e18000-b7bf-11e8-9929-8b5e8817e6ee.GIF)
During test, the application, warm "no UserPool".
Application : https://github.com/aws-samples/aws-amplify-graphql
Branch : Master

Androidstudio 3.1.4
npm : 6.4.1
aws-amplify-react@0.1.54

Regards,

Tony

**Comment by robmurtagh** [comment]
I get the same error. Presumably it's related to:

```javascript
Amplify.configure(awsmobile);
```

**Comment by elorzafe** [comment]
There was an issue with aws-sdk, I've just update that repo with the fix. Feel free to reopen in case the issue persist
