### ISSUE TITLE
Work on an AppSync API from a code editor

### ISSUE THREAD

**Issue by adrianwe** [awslabs/aws-mobile-appsync-sdk-js#257]
Hey guys,

I am building a GraphQL server with AppSync and I really like it. However, as my schema and resolvers grow, I find it more and more difficult to work on it in the AWS management console.

The best thing that happened to me was a sudden logout from AWS (for whatever reason) causing me to lose hours of unsaved changes to my schema. I didn't save on purpose because I was refactoring my schema, changing type names etc., and if you save then you're messing up (or deleting) your resolvers as well. Let's say I was a little "surprised" to find out that there was no autosave at all and after I logged back in everything was gone (and I didn't have any chance to anticipate this sudden logout either). As already mentioned there is also this other issue that you cannot rename types or operations because this will delete all associated resolvers! So you carefully have to go back and forth between resolvers and schema to copy resolvers, change the name and then paste them back in. Have fun if you have several resolvers attached to one type. You will need to paste them somewhere else as a step in between.

So, I appreciate the idea of working in the cloud and there are also many advantages I really appreciate, but at the current state it would be much nicer to work on the files in a code editor and then push the changes to the web view for further adjustments that are only possible there. Is there a way to do that with AppSync?

I also find the query section quite limiting where I cannot even save any queries to rerun for testing. I would really like to use something like GraphiQL or GraphQL Playground to query my AppSync API where you have a history and can also save queries. Any advice on how to set this up? I didn't get it to work and also didn't find any anwers on that anywhere.

**Comment by undefobj** [comment]
Have you checked out AWS Amplify?

https://aws-amplify.github.io

Amplify has a CLI Toolchain which you can annotate GraphQL SDL from your local client and deploy/update the backend. Take a look at the transformer docs here:
https://github.com/aws-amplify/amplify-cli/blob/master/how-to-write-a-transformer.md

Video here:
https://www.youtube.com/watch?v=r0PbwDoNMcY

**Comment by adrianwe** [comment]
Thanks for your reply! Yeah, I have had a look at the Amplify CLI before, but not sure if it's what I'm looking for if I understand it correctly. Isn't that similar to something like [this](https://docs.aws.amazon.com/appsync/latest/devguide/provision-from-schema.html?shortFooter=true#existing-schema) where your data sources and resolvers are provisioned for you automatically after you designed your schema? That's not really an option for me as I need full control over these things. What I had in mind is much simpler, just a way to edit your existing code (for the schema and the resolvers) in the editor instead of the management console without any further magic. ;-) If I understand it correctly, you can't directly edit request and response mapping templates from the Amplify CLI, right?

**Comment by undefobj** [comment]
The CLI will allow for some of this and is being worked on. Our story around local development as you describe is the Amplify CLI so if you're looking for features you should comment in that repo. For example I believe this is what you are asking for: https://github.com/aws-amplify/amplify-cli/issues/74#issuecomment-418169901

It would make sense to comment in that issue or open a new one if different functionality is needed so that your feedback could go into that work.

BTW it's not magic, in fact we actually expose how it all works using CloudFormation and you can even write your own transformer which we encourage: https://github.com/aws-amplify/amplify-cli/blob/master/how-to-write-a-transformer.md

**Comment by adrianwe** [comment]
Yes, I believe that's exactly what I'm looking for! Cool, will keep an eye on Amplify CLI then. Will comment there if some further needs arise on my side.

**Comment by imolorhe** [comment]
I know this is an old issue, but I think the [Altair GraphQL client](https://altair.sirmuel.design/) would help here as well. _It also supports subscriptions for AppSync_
