### ISSUE TITLE
Mutation error: Object.items read-only

### ISSUE THREAD

**Issue by luke0b1000** [awslabs/aws-mobile-appsync-sdk-js#261]
I follow the code in the README.md with simpler modifications. I was able to view the query no issues, when I submit the mutation, the code works and the subscription works (it shows up in dynamodb and browser), but receive the error on the console. Different error if switch to without graphqlMutation.
I put a breakpoints there, with Object.getOwnPropertyDescriptors(obj) and on the second pass I get "writable: false" along with error.

Error in Dev-Tools
 TypeError: Cannot assign to read only property 'items' of object '#<Object>'
    at offline.js:186
    at Array.reduce (<anonymous>)
    at setValueByPath (offline.js:184)
    at offline.js:282
    at Array.forEach (<anonymous>)
    at _loop_1 (offline.js:259)
    at update (offline.js:288)
    at store.js:122
    at tryFunctionOrLogError (errorHandling.js:3)
    at store.js:122
    at MyCache../node_modules/apollo-cache-inmemory/lib/inMemoryCache.js.InMemoryCache.performTransaction (inMemoryCache.js:179)
    at DataStore../node_modules/apollo-client/data/store.js.DataStore.markMutationResult (store.js:121)
    at Object.next (QueryManager.js:198)
    at notifySubscription (Observable.js:126)
    at onNotify (Observable.js:161)
    at SubscriptionObserver.next (Observable.js:215)
    at notifySubscription (Observable.js:126)
    at flushSubscription (Observable.js:112)
    at Observable.js:156
    at Observable.js:67

package.json

>     "aws-appsync": "^1.3.4",
>     "aws-appsync-react": "^1.1.4",
>     "graphql-tag": "^2.9.2",
>     "react": "^16.5.2",
>     "react-apollo": "^2.2.3",
>     "react-dom": "^16.5.2",
>     "react-scripts": "1.1.5",
>     "uuid": "^3.3.2"

https://gist.github.com/luke0b1000/b061a6d5a30bae4e06113433705e35d9

**Comment by HerbCaudill** [comment]
Running into this as well. Repo here: 
https://github.com/HerbCaudill/appsync-todos/tree/%23261

**Comment by HerbCaudill** [comment]
I suspect this is the culprit: https://github.com/apollographql/apollo-client/issues/1909

**Comment by elorzafe** [comment]
Hi @HerbCaudill  thanks for sharing your repo. I did a fork of yours and added subscriptions to it and works without issues (no console errors). https://github.com/elorzafe/appsync-todos/

I have this schema on my api (I changed the type of status to String)

```graphql
input CreateTodoInput {
	name: String
	description: String
	status: String
}

input DeleteTodoInput {
	id: ID!
}

type Mutation {
	createTodo(input: CreateTodoInput!): Todo
	updateTodo(input: UpdateTodoInput!): Todo
	deleteTodo(input: DeleteTodoInput!): Todo
}

type Query {
	getTodo(id: ID!): Todo
	listTodos(filter: TableTodoFilterInput, limit: Int, nextToken: String): TodoConnection
}

type Subscription {
	onCreateTodo: Todo
		@aws_subscribe(mutations: ["createTodo"])
	onUpdateTodo: Todo
		@aws_subscribe(mutations: ["updateTodo"])
	onDeleteTodo(
		id: ID,
		name: String,
		description: String,
		status: String
	): Todo
		@aws_subscribe(mutations: ["deleteTodo"])
}

input TableBooleanFilterInput {
	ne: Boolean
	eq: Boolean
}

input TableFloatFilterInput {
	ne: Float
	eq: Float
	le: Float
	lt: Float
	ge: Float
	gt: Float
	contains: Float
	notContains: Float
	between: [Float]
}

input TableIDFilterInput {
	ne: ID
	eq: ID
	le: ID
	lt: ID
	ge: ID
	gt: ID
	contains: ID
	notContains: ID
	between: [ID]
	beginsWith: ID
}

input TableIntFilterInput {
	ne: Int
	eq: Int
	le: Int
	lt: Int
	ge: Int
	gt: Int
	contains: Int
	notContains: Int
	between: [Int]
}

input TableStringFilterInput {
	ne: String
	eq: String
	le: String
	lt: String
	ge: String
	gt: String
	contains: String
	notContains: String
	between: [String]
	beginsWith: String
}

input TableTodoFilterInput {
	id: TableIDFilterInput
	name: TableStringFilterInput
	description: TableStringFilterInput
	status: TableStringFilterInput
}

type Todo {
	id: ID!
	name: String
	description: String
	status: String
}

type TodoConnection {
	items: [Todo]
	nextToken: String
}

input UpdateTodoInput {
	id: ID!
	name: String
	description: String
	status: String
}
```

**Comment by elorzafe** [comment]
@HerbCaudill which browser are you using?

**Comment by HerbCaudill** [comment]
Chrome 69.0.3497.100 . 

FWIW I was able to get this working by forking aws-mobile-appsync-sdk-js and updating the version of `apollo-client` to 2.4.2, which doesn't deep-freeze items returned from queries. https://github.com/awslabs/aws-mobile-appsync-sdk-js/compare/master...HerbCaudill:master

**Comment by michaelcaterisano** [comment]
Hi @HerbCaudill. Noob question for you. I'm having the same issue. I tried forking and updating apollo-client as well, but am a little confused how to include the fork in my package.json. Tips?

**Comment by elorzafe** [comment]
We have fixed this on the latest release (aws-appsync@1.4.0) I will close the issue for now, but feel free to create a new issue if this problem persist.
