### ISSUE TITLE
Can't Pass Cookies from Localhost to AppSync GraphQL

### ISSUE THREAD

**Issue by sconzof** [awslabs/aws-mobile-appsync-sdk-js#265]
I tried passing `credentials = 'include'` and also tried passing `credentials = 'same-origin'` to the AppSyncClient constructor, but the graphQL requests are not passing cookies in the http request.
What is the right way to tell AppSync to tell Apollo HttpLink to use the credentials setting mentioned here: https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-http#options

```
import Client from 'aws-appsync';
...
  const appSyncClient = new Client({
    url: config.graphqlEndpoint,
    region: config.region,
    auth: {
      type: 'API_KEY',
      apiKey: config.apiKey,
      credentials: 'include',
    },
  });
```

*Background*
I am using AppSync `aws-appsync` with GraphQL `react-apollo` and I'm trying to make sure that while I'm doing local development, cookies that are set for my app's domain (eg: https://app.example.com) are passed to the AppSync API. (The reason for this is because I'm proxying graphql traffic through an ELB, and am using a Listener with Auth and Cognito on the AWS ELBs, so the AWSELBAuthSession cookies need to be passed along).

I created an entry in my /etc/hosts file (127.0.0.1 local.app.example.com), and run my app on localhost:3000 with nginx in front of it using https://local.app.example.com/, on port 443. So I'm trying to make sure that the browser session https://local.app.example.com passes that cookies that were set by https://app.example.com/.

Any thoughts?
Thank you.

**Comment by sconzof** [comment]
Perhaps a clarification on the request will help?

It would be very helpful if the AppSync constructor allowed me to pass options to the `fetcher` used by `apollo-link-http`, such as `credentials: include`, and `mode: cors`, and a bonus would be `headers: { ... }` where I could do something like `{ 'x-impersonalte-user': 'AWSome_user' }`. It looks like currently, only the `url` is passed to the `createHttpLink` method, here: https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/edf31ddf6cc788beb24f11687c0094f15de5321d/packages/aws-appsync/src/client.ts#L61

Can the constructor be expanded to support sending other options to the Apollo link object?

This would help tremendously with running development environments locally, which try to mimic production environments where we utilize AWS ELB's which provide credentials via the `Auth` rules in a `Listener`. Also, it would allow me to set additional headers that could be passed along to the `VTL` code, which currently looks for `$ctx.identity.username`, but I would like to set other headers in the React client to assist with testing AppSync, or impersonating other users to reproduce issues in our dev or staging environments (hence the suggestion about adding something like an `x-impersonate-user` header.

**Comment by manueliglesias** [comment]
Hi @sconzof 

You can try something like this:

```typescript
const link = createAppSyncLink({
  url: appSyncConfig.graphqlEndpoint,
  region: appSyncConfig.region,
  auth: {
    type: appSyncConfig.authenticationType,
    apiKey: appSyncConfig.apiKey
  },
  resultsFetcherLink = createHttpLink({ 
    uri: appSyncConfig.graphqlEndpoint,
    // ...other options like:
    // headers: { ... }
  })
});

const client = new AWSAppSyncClient({}, { link });
```


Let me know how it goes!
