### ISSUE TITLE
Access resolver `info` object in Lambda function/mapping template

### ISSUE THREAD

**Issue by schickling** [awslabs/aws-mobile-appsync-sdk-js#27]
I'm looking into using [graphql-binding](https://github.com/graphql-binding/graphql-binding) within Lambda functions using AppSync. For this to work across multiple levels of "type-nesting" I need access to the [`info` object](https://www.apollographql.com/docs/graphql-tools/resolvers.html#Resolver-function-signature) provided by the GraphQL engine.

**Comment by undefobj** [comment]
Thank you for the feedback. At this time we don't provide this object in the service but will take a look for the future.

**Comment by schickling** [comment]
@undefobj can you please re-open this issue until this is supported so other people can chime in with their thoughts?

**Comment by undefobj** [comment]
Hi @schickling this is a repo for the JavaScript SDK and this feature request is specifically related to the service, not the client SDK. We've added the request into our backlog, but we try to track open issues related to the JS SDK in this location. If you'd like to have a service specific request that you'd like to have others comment on that would be best posted in the AWS forums: https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0
