### ISSUE TITLE
Example of usage from vanilla JS

### ISSUE THREAD

**Issue by kad3nce** [awslabs/aws-mobile-appsync-sdk-js#271]
Hey there! I am using AppSync to gather metrics from a simple video player plugin. So, in this case, I'm not using a framework like React or Vue…just vanilla JS.

I simply need to create a connection to AppSync and send data over it (one way at this point).

I'm finding myself getting lost trying to translate the examples of React and Vue usage into straightforward JavaScript.

Are there any examples of bootstrapping a vanilla JS project to communicate with and send data into AppSync?

**Comment by elorzafe** [comment]
Hi @kad3nce I suggest you to take a look on AWS Amplify. API Category provides a simple way to make calls to AppSync. Take a look [here](https://aws-amplify.github.io/amplify-js/media/api_guide.html#mutations)

Let me know how it goes

**Comment by kad3nce** [comment]
That’s exactly what I was looking for. Thanks!
