### ISSUE TITLE
Error running aws-appsync on Node.js

### ISSUE THREAD

**Issue by JonathanHolvey** [awslabs/aws-mobile-appsync-sdk-js#276]
I'm getting a TypeError when using aws-appsync on Node.js to make a GraphQL query;

> `readQueryFromStore` is not a function.

```
Error: Network error: apollo_cache_inmemory_1.readQueryFromStore is not a function
    at new ApolloError (/home/node/app/node_modules/apollo-client/bundle.umd.js:85:32)
    at /home/node/app/node_modules/apollo-client/bundle.umd.js:1039:45
    at /home/node/app/node_modules/apollo-client/bundle.umd.js:1414:21
    at Array.forEach (<anonymous>)
    at /home/node/app/node_modules/apollo-client/bundle.umd.js:1413:22
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (/home/node/app/node_modules/apollo-client/bundle.umd.js:1408:26)
    at /home/node/app/node_modules/apollo-client/bundle.umd.js:988:35
    at <anonymous>
  graphQLErrors: [],
  networkError: TypeError: apollo_cache_inmemory_1.readQueryFromStore is not a function
    at processOfflineQuery (/home/node/app/node_modules/aws-appsync/lib/link/offline-link.js:155:40)
    at /home/node/app/node_modules/aws-appsync/lib/link/offline-link.js:112:28
    at new Subscription (/home/node/app/node_modules/zen-observable/lib/Observable.js:183:34)
    at Observable.subscribe (/home/node/app/node_modules/zen-observable/lib/Observable.js:262:14)
    at /home/node/app/node_modules/aws-appsync/lib/client.js:120:67
    at <anonymous>
```

This is the basis of the code that I'm running that causes the error, which is produced when calling `query()`:

```javascript
const AppSyncClient = require('aws-appsync').default
const fetch = require('node-fetch')
const client = new AppSyncClient(config)

const data = client.hydrated().then(hclient => (
  hclient.query({ query }) // Error thrown here
    .catch(console.error)
))
```

Here are the dependancies I have specified in `package.json`:

```json
"dependencies": {
    "aws-appsync": "1.4.0",
    "aws-sdk": "2.341.0",
    "graphql-tag": "2.10.0",
    "node-fetch": "2.2.0"
}
```

The same code runs correctly in Chrome when bundled and included in a `<script>` tag.

Should it work when running in Node.js, and What can I do to fix it?

**Comment by SebSchwartz** [comment]
Check the code example here: https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-node.html

You need to require 'isomorphic-fetch'
And put the other global stuffs so the appsync client will be compatible on nodejs.

**Comment by JonathanHolvey** [comment]
Thanks for that. Adding the `global.window` object now allows my GraphQL queries to succeed.

However, it looks like the `global.localStorage` object isn't being recognised correctly, as I'm now getting the following warning:

> redux-persist asyncLocalStorage requires a global localStorage object. Either use a different storage backend or if this is a universal redux application you probably should conditionally persist like so: https://gist.github.com/rt2zz/ac9eb396793f95ff3c3b

I've also tried using `global.localStorage = require('node-localstorage')`, with the same result.

**Comment by SebSchwartz** [comment]
As described in this issue: https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/227

You can disable the offline on the client object. I suppose you won't need it?

```javascript
const client = new AWSAppSyncClient({
    url: AppSync.graphqlEndpoint,
    region: AppSync.region,
    auth: {
        type: AUTH_TYPE.API_KEY,
        apiKey: AppSync.apiKey,
    },
    disableOffline: true
});

```

**Comment by JonathanHolvey** [comment]
Actually, the offline feature is the primary reason for my user of AppSync. Will it be possible to get it working with Node?

I've tried supplying an instantiated redux-persist storage object (redux-persist-node-storage) to the aws-appsync's offline config  `storage` option, but this causes the app to hang when making a GraphQL query. I haven't been able to dig deeper with debugging this yet.

**Comment by SebSchwartz** [comment]
Seems to be the good store option for node.
Maybe it's a simple error like the write access to the specified file path of the store?

**Comment by ayushchd** [comment]
We're using an older version of `redux-offline` and as a result, an older version of `redux-persist`. The older version expects the storage functions to support callbacks and also expects storage engines to define a method `getAllKeys`. 

For now, you can get around by either writing a custom `localStorage` that expects a callback parameter in all its methods and invokes the callback after the op is completed or you can downgrade to `v1.0.2` of `redux-persist-node-storage`:

```
npm install --save redux-persist-node-storage@1.0.2
```
You can take a look at the older implementation [here](https://github.com/pellejacobs/redux-persist-node-storage/blob/377bdf928ce5b8ca24a117e577acd53201e82e30/src/index.ts).

**Comment by JonathanHolvey** [comment]
Thanks @ayushchd, using redux-persist-node-storage version 1.0.2 got it working!

Offline seems to be working correctly and mutations are successfully sent when the connection is restored, even if the Node server is restarted in between.

There are lots of scenarios to test to ensure it will always work, but so far I'm pretty pleased.

**Comment by undefobj** [comment]
@JonathanHolvey is your issue resolved and we can close this issue now?

**Comment by JonathanHolvey** [comment]
I'm happy to close it. However there was a comment about updating redux-persist, which I'm not sure has been discussed.

**Comment by manueliglesias** [comment]
> @manueliglesias We should update the NodeJS client tutorial to address this and also upgrade to the latest version of `redux-offline`

Agree, I'll create a new issue for the redux-offline upgrade and close this one
