### ISSUE TITLE
Incorrect types in outdated version of redux-offline

### ISSUE THREAD

**Issue by mwarger** [awslabs/aws-mobile-appsync-sdk-js#279]
**Do you want to request a *feature* or report a *bug*?**
Bug involving incorrect types

**What is the current behavior?**
Incorrect types for redux-offline causes compilation error

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Compilation fails in typescript because of an outdated redux-offline dependency.  Current master uses 2.2.1 (this is a year old) and current types are fixed on version 2.5 (latest release)

**What is the expected behavior?**
No compilation errors based on incorrect types.

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**
See above.

I'm willing to PR this - have it forked.  Will proceed for now as I didn't see any recent fixes for this issue.

Any doubts about feasibility of updating the redux-offline dependency?

**Comment by mwarger** [comment]
Sorry, I meant to say compilation fails, not package installation fails. I've edited my comment. I will revisit this issue tomorrow and see if I can clarify further.

**Comment by manueliglesias** [comment]
Hi @mwarger

I'll close this issue in favor of #280
