### ISSUE TITLE
Pagination with Lambda example

### ISSUE THREAD

**Issue by sid88in** [awslabs/aws-mobile-appsync-sdk-js#28]
It will be EXTREMELY helpful to get an example on how to do pagination using Lambda integration.

One use case can be Lambda integrates with REST API or any other backend which handles pagination (which is easier because you can then have your backend handle pagination) but would be great to see how to handle pagination using appsync when backend doesn't have built-in support for the same. 

thanks
Sid

**Comment by alez007** [comment]
Well, If I were in your shoes, the way I'm handling pagination in the backend will be the way I'll handle pagination in appsync. First of all, make sure you read the [documentation](https://docs.aws.amazon.com/appsync/latest/devguide/designing-your-schema.html) about designing your schema. If you store data in dynamoDB, it's pretty much copy paste from documentation, you keep track of the last returned token that dynamodb gives you anyway at the end of your query, then pick up from there on the next page. 

Now, let's presume your REST api has pagination like ?page=<number>&limit=<number>. I would just create a query like this: 

`
type Query {
    query Items(input: ItemsInput): PaginatedItems
}

input ItemsInput {
    page: Int
    limit: Int
}

type PaginatedItems {
    items: [Item]
    nextPage: Int
}
`
If you'll attach a lambda resolver to the query with the input as $context.arguments.input and default output, then the 'event' object in lambda function will either be empty (if you query without parameters) or it will contain {page: <number>, limit: <number>}.

I hope this helps.

**Comment by sid88in** [comment]
@alez007 totally. thanks. The above approaches make sense when your backend does the pagination for you i.e DynamoDB or REST API or RDBMS (offset). But I was wondering how pagination would work if your backend doesn't handle these aspects.

**Comment by elorzafe** [comment]
@sid88in I didn't follow your question completely. I think the only way is that the backend do the pagination somehow. And your lambda function must send the request in the form that the backend can understand.

**Comment by harleyguru** [comment]
Hi @elorzafe @sid88in , @alez007

Here is my situation:
- I set up lambda resolver for one field, and this lambda will query to DDB and get paginated data.
- Lambda needs to process fetched data from DB and prepare the response
- But this response has a lot of data set.
- I need to paginate this dataset again on lambda.

What can I do to accomplish this?

**Comment by elorzafe** [comment]
@harleyguru is an interesting use case.

I think the best way to handle this is to have a trigger on your dynamo table that do this process and store the data on a different table and do the query from there.

**Comment by elorzafe** [comment]
@sid88in I will close the issue for now, but feel free to open or create a new one.
