### ISSUE TITLE
Mutations instantly rollback

### ISSUE THREAD

**Issue by builtbyproxy** [awslabs/aws-mobile-appsync-sdk-js#281]
**Bug**

**What is the current behavior?**
Whenever I mutate using apollo's mutate component it instantly rolls back the mutation as seen here: 
![Action Log](https://i.gyazo.com/014e53fdcbf06358d81e5430823f214d.gif)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

If you implement any mutation with Apollo, the perfect one is [this](https://www.apollographql.com/docs/react/features/optimistic-ui.html) then it will always roll back. I have encountered this when using the mutation component, when using HOCs. Something is wrong with my client configuration I think.

This mutation never even hits my server.

My current client configuration is: 
```
// Apollo Imports
import { ApolloLink } from 'apollo-link';
import { withClientState } from 'apollo-link-state';
import { ApolloProvider } from 'react-apollo';
import { InMemoryCache } from "apollo-cache-inmemory"
import { persistCache } from 'apollo-cache-persist';

// Appsync Imports
import AWSAppSyncClient, { createAppSyncLink, createLinkWithCache } from "aws-appsync";
import { Rehydrated } from 'aws-appsync-react';
import { AUTH_TYPE } from "aws-appsync/lib/link/auth-link";

const cache = new InMemoryCache();
persistCache({
    cache,
    storage: AsyncStorage,
});

const stateLink = createLinkWithCache(() => withClientState({
    cache
}));

const awsAppSyncLink = createAppSyncLink({
    url: 'http://localhost:60004/graphql'
    region: AWS_REGION,
    auth: {
        type: AUTH_TYPE.AMAZON_COGNITO_USER_POOLS,
        apiKey: APPSYNC_API_KEY,
        jwtToken: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'
    },
});

const link = ApolloLink.from([stateLink, awsAppSyncLink]);

const client = new AWSAppSyncClient({}, { link });

class ApolloApp extends Component {
    constructor(props) {
        super(props);
    }

    render() {
        return (
            <ApolloProvider client={client}>
                <Rehydrated>
                    <App />
                </Rehydrated>
            </ApolloProvider>
        )
    }
}

export default AppRegistry.registerComponent('App', () => ApolloApp);
```

**What is the expected behavior?**

It should hit my server and mutate my database.

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**

- React-Native
- Apollo
- Appsync
- Serverless

**Versions:**
```
"dependencies": {
    "@types/react-navigation": "^2.0.24",
    "apollo-boost": "^0.1.16",
    "apollo-cache-inmemory": "^1.3.5",
    "apollo-cache-persist": "^0.1.1",
    "apollo-link": "^1.2.3",
    "apollo-link-http-common": "^0.2.5",
    "apollo-link-state": "^0.4.2",
    "aws-amplify": "^1.1.5",
    "aws-amplify-react-native": "^2.0.5",
    "aws-appsync": "^1.3.4",
    "aws-appsync-react": "^1.1.4",
    "date-fns": "^1.29.0",
    "graphql": "^14.0.2",
    "react": "16.5.0",
    "react-apollo": "^2.2.4",
    "react-native": "0.57.0",
    "react-native-camera": "^1.3.1",
    "react-native-dotenv": "^0.2.0",
    "react-native-vector-icons": "^5.0.0",
    "react-native-version-number": "^0.3.4",
    "react-navigation": "^2.17.0",
    "subscriptions-transport-ws": "^0.9.15",
    "tslint": "^5.11.0"
  },
```

I should note, my serverless and appsync are all running offline (my jwt is fake) and my queries work fine, only my mutations roll back.

Any help would be incredibly appreciated
Thankyou!

**Comment by builtbyproxy** [comment]
Additionally, this works perfectly fine using GraphiQL

**Comment by haverchuck** [comment]
@builtbyproxy Are you getting an output (errors, etc) in the network request?

**Comment by builtbyproxy** [comment]
@haverchuck 
I have been meaning to get back to this issue.
I actually solved it. My chrome debugger wasnt showing anything in the network tab HOWEVER with the use of [React-Native-Debugger](https://github.com/jhen0409/react-native-debugger) my network inspector would show a failed network response.

Long story short the issue was with my optimistic response and it wasn't matching what was expected in the query and therefore it was rolling back.
