### ISSUE TITLE
Signing URLs using IAM authentication in combination with a relative `aws_appsync_graphqlEndpoint` breaks.

### ISSUE THREAD

**Issue by philiiiiiipp** [awslabs/aws-mobile-appsync-sdk-js#285]
**Do you want to request a *feature* or report a *bug*?**
bug 

**What is the current behavior?**

I want to run my appsync service behind a cloudfront distribution. I am using a relative path for the graphql endpoint.

```
const config = {
  Auth: {
    mandatorySignIn: true,
    identityPoolId: AWS_COGNITO_IDENTITYPOOL_ID,
    region: AWS_REGION,
    userPoolId: AWS_COGNITO_USERPOOL_ID,
    userPoolWebClientId: AWS_COGNITO_USERPOOL_WEBCLIENT_ID,
  },
  aws_appsync_graphqlEndpoint: '/graphql',
  aws_appsync_region: AWS_REGION,
  aws_appsync_authenticationType: APPSYNC_AUTH_TYPE,
};
```

This works fine when using `cognito user pools` as the `aws_appsync_authenticationType`. Using IAM though I am running into troubles when signing the url. It seems as if it does not accept a relative path

```
signer.js?599d:88 Uncaught (in promise) TypeError: Cannot read property 'match' of null
    at parse_service_info (signer.js?599d:88)
    at Function.sign (signer.js?599d:210)
    at Object.eval (auth-link.js?1caa:156)
    at step (auth-link.js?1caa:56)
    at Object.eval [as next] (auth-link.js?1caa:37)
    at fulfilled (auth-link.js?1caa:28)
```

At this line https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/7a3f5cec214ea4a7c64a41c9106967e2e2fad0fc/packages/aws-appsync/src/link/signer/signer.ts#L95
 
```
var parse_service_info = function (request) {
    var url_info = url.parse(request.url), host = url_info.host;
    var matched = host.match(/([^.]+)\.(?:([^.]*)\.)?amazonaws\.com$/), parsed = (matched || []).slice(1, 3);
    if (parsed[1] === 'es') { // Elastic Search
        parsed = parsed.reverse();
    }
    return {
        service: request.service || parsed[0],
        region: request.region || parsed[1]
    };
};
```

I think there should be an earlier return if the url cannot be parsed, e.g. if it is a relative url.

**Comment by undefobj** [comment]
AppSync already has a protected CDN built in for you so a CloudFront distribution isn't needed and might end up causing some issues with features. Is there a reason you're trying to do this? It's not going to give any additional benefits other than potentially more latency.

**Comment by philiiiiiipp** [comment]
I wouldnt say that there is anything which I cannot work around. Just out of curiosity, which features might have problems with that? Appart from the way the signing is done now.

**Comment by undefobj** [comment]
It's hard to say specifically, but as you've already seen you're impacting some DNS assumptions with this activity and changing the client behavior isn't the right solution. If there's a reason you're trying to put another CDN in front that should probably be raised in the [AppSync forum](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0).

**Comment by philiiiiiipp** [comment]
Alright, I will close this then.
