### ISSUE TITLE
RetryLink keeps retrying even if 401 is thrown

### ISSUE THREAD

**Issue by nealyip** [awslabs/aws-mobile-appsync-sdk-js#308]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

RetryLink keeps retrying even if 401 is thrown

![app-sync](https://user-images.githubusercontent.com/6487585/49352736-7af30480-f6f4-11e8-8fc8-fc41889fefe1.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

AppSync returns 401 if the given token has expired or invalid.
For the following codes
```
const options = {
    query: getPosts,
    fetchPolicy: 'network-only'
};
const args = {
    url: 'https://<some id>.appsync-api.ap-northeast-1.amazonaws.com/graphql',
    region: 'ap-northeast-1',
    auth: {
        type: AUTH_TYPE.OPENID_CONNECT,
        jwtToken: async () => 'some invalid token'
    }
};
const client = new AWSAppSyncClient(args);
const observable = client.watchQuery(options);

observable.subscribe(console.log, err=>{
if (err.networkError && err.networkError.statusCode === 401) {
// handle re-login logic
}
}, console.log);
```

It resumes catching 401 error on the error handler immediately if I comment the retry link from node_modules/aws-appsync/lib/client.js
retry_link_1.createRetryLink(apollo_link_1.ApolloLink.from([

**What is the expected behavior?**
From app-sync@1.4.0 the error handler is triggered immediately once 401 error is thrown without retrying.

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**
app-sync@1.5.1
nodejs@8.10

**Comment by manueliglesias** [comment]
Thank you @nealyip 

A fix is on the way

**Comment by nealyip** [comment]
Thanks for the quick fix.
