### ISSUE TITLE
IAM auth in AWS Lambda function

### ISSUE THREAD

**Issue by r3-yamauchi** [awslabs/aws-mobile-appsync-sdk-js#309]
I want to call AppSync API with IAM auth in AWS Lambda function.
my code times out.
```
require('isomorphic-fetch');
const AUTH_TYPE = require('aws-appsync/lib/link/auth-link').AUTH_TYPE;
const AWSAppSyncClient = require('aws-appsync').default;
const AWS = require('aws-sdk');
const gql = require('graphql-tag');

const listMessages = gql(`
  query getConversationMessages($conversationId: ID!, $after: String, $first: Int) {
    allMessageConnection(conversationId: $conversationId, after: $after, first: $first) {
      __typename
      nextToken,
      messages {
        __typename
        id
        conversationId
        content
        createdAt
        sender
        isSent
      }
    }
  }`);

exports.handler = async (event) => {
    const client = new AWSAppSyncClient({
        url: process.env['URL'],
        region: process.env['REGION'],
        auth: {
            type: AUTH_TYPE.AWS_IAM,
            credentials: AWS.config.credentials
        },
        disableOffline: true
    });

    const param = {
        conversationId: "hello",
        after: null,
        first: 20
    };

    try {
        const result = await client.query({
            query: listMessages,
            variables: param,
            fetchPolicy: 'network-only'
        });
        console.log(JSON.stringify(result));
        return result;
    } catch (err) {
        console.log(JSON.stringify(err));
        return err;
    }
};
```

AUTH_TYPE.API_KEY and AMAZON_COGNITO_USER_POOLS is OK in AWS Lambda func.
How can I use AUTH_TYPE.AWS_IAM?

In other issues, 
```
  auth: {
    type: AUTH_TYPE.AWS_IAM,
    credentials: () => Auth.currentCredentials(),
  },
```
but, I don't use Amplify lib in AWS Lambda func.

my other NG cases
```
const credentials = {
  accessKeyId: process.env['AWS_ACCESS_KEY_ID'],
  secretAccessKey: process.env['AWS_SECRET_ACCESS_KEY'],
  sessionToken: process.env['AWS_SESSION_TOKEN']
};
```
and
```
const credentials = async () => {
  return new Promise((resolve, reject) => {
      resolve(
          new AWS.Credentials({
              accessKeyId: process.env['AWS_ACCESS_KEY_ID'],
              secretAccessKey: process.env['AWS_SECRET_ACCESS_KEY'],
              sessionToken: process.env['AWS_SESSION_TOKEN']
          })
      );
  });
};
```
```
        auth: {
            type: AUTH_TYPE.AWS_IAM,
            credentials: credentials
        },
```
my lambda func, Task timed out after 30.02 seconds.

**Comment by OlivierPT** [comment]
Hi, here is the code I successfully to make Graphql call to AppSync with IAM AUTH from a Lamdba. Hope it can help you:

`require('isomorphic-fetch');`

`// Require AppSync module`
`import AWS from 'aws-sdk/global'`;
`const AUTH_TYPE = require('aws-appsync/lib/link/auth-link').AUTH_TYPE;`
`const AWSAppSyncClient = require('aws-appsync').default;`
`const gql = require('graphql-tag');`

`const AppSyncConfig = {`
    `url: process.env.GRAPHQL_API_URL,`
    `region: process.env.REGION,`
    `auth: {`
       ` type: AUTH_TYPE.AWS_IAM,`
        `credentials: AWS.config.credentials,`
    `},`
    `disableOffline: true,`
  `};`

`const options = {`
      `defaultOptions: {`
       ` query: {`
          `fetchPolicy: 'network-only',`
          `errorPolicy: 'all',`
        `},`
      `},`
   ` };`

`// Set up Apollo client`
`const client = new AWSAppSyncClient(AppSyncConfig, options);`

**Comment by r3-yamauchi** [comment]
Thanks.

The reason why my code did not work is 

in my schema,

```
type schema {
	query: Query
	mutation: Mutation
	subscription: Subscription
}
```

Correctly

```
schema {
	query: Query
	mutation: Mutation
	subscription: Subscription
}
```

This problem has been fixed in https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular/commit/256f1cac6b8683abeb8e476bce95c54b205330d0#diff-c8c6c159798cd7a937882ce922562af8

**but**, in AppSync management console "Create API" - "Start from a sample project" - "Chat App" template  is **still wrong and causes problems**...

**Comment by undefobj** [comment]
@r3-yamauchi thanks for letting us know the console sample has this issue. I've raised it with the AppSync console team and we'll get a fix released. Closing this issue for now as your issue is resolved.
