### ISSUE TITLE
IAM policy for IAM mode?

### ISSUE THREAD

**Issue by nicokruger** [awslabs/aws-mobile-appsync-sdk-js#31]
Hi there,

I am trying to get IAM authentication to work.

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "appsync:GraphQL"
            ],
            "Resource": [
                "arn:aws:appsync:us-east-1:xxxxxxxx:/apis/YourAppName/*"
            ]
        }
    ]
}

I'm struggling to see where I can easily find the ARN for the graphql endpoint. I'm trying it as follows:

xxxxxxxxxx - the AWS account id (xxxx-xxxx-xxxx)

Then the YourAppName - is that the name of the AppSync endpoint in the console, or is it it the https://xxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql part in the endpoint URL?

Thanks

**Comment by nicokruger** [comment]
Changing the resource to "*" works - so maybe I'm just being dumb but it's not too obvious to me what the ARN should be exactly.

**Comment by karthiksaligrama** [comment]
There is currently a bug in the docs with regards to the resource arn.

```
arn:aws:appsync:us-east-1:xxxxxxxx:apis/YourAppName/*
```

instead of 

```
arn:aws:appsync:us-east-1:xxxxxxxx:/apis/YourAppName/*
```

Notice the '/' in front of `apis`

**Comment by nicokruger** [comment]
Ah thanks! I never would have caught that.

Will try it out and close as soon as I can. YourAppName is the name in the AppSync console correct?

**Comment by karthiksaligrama** [comment]
Yes that is correct

**Comment by nicokruger** [comment]
Will it work if there are spaces in the name?

**Comment by karthiksaligrama** [comment]
apologies i misspoke. You need to use your apiId instead AppName. I updated the comment above

**Comment by nicokruger** [comment]
Thanks, I got it working.

So to sum up, the '/' should *not* be in front of the "apis" part. I think you had it mixed up above :)

What ended up working was:

> arn:aws:appsync:us-east-1:xxxxxxxxxx:apis/<YourGraphQLApiId>/*

where xxxxxx is the amazon account number, and YourGraphQLApiId is the ID displayed on the console beneath the endpoint's name.

Thanks!
