### ISSUE TITLE
[Request] Update of apollo-cache-inmemory to 1.3.12

### ISSUE THREAD

**Issue by misterbridge** [awslabs/aws-mobile-appsync-sdk-js#334]
**Do you want to request a *feature* or report a *bug*?**
Update of dependency package for bug fix

**What is the current behavior?**
Memory leak in optimistic response

Thank you to update apollo-cache-inmemory to 1.3.12
https://github.com/apollographql/apollo-client/issues/4210

**Comment by jrounsav** [comment]
This yarn feature was new to me so I'm posting here.
We couldn't wait on the PR. Added the following to our package.json and ran yarn install to override the dependency.
```
"resolutions": {
    "apollo-cache-inmemory": "1.3.12"
  }
```

**Comment by biker2000on** [comment]
This is still a major issue in using Appsync Client. When running multiple mutations and writing to the cache with Optimistic Response, the app quickly runs out of memory and Chrome stops with the out of memory error eventually shutting down the page. 

As mentioned above, the dependency for `apollo-cache-inmemory` needs to be updated to at least 1.3.12 to mitigate the issue. 

https://github.com/apollographql/apollo-client/issues/4210

**Comment by misterbridge** [comment]
Looks like fixed, thx
