### ISSUE TITLE
AppSync S3Object Wont Upload in React-Native

### ISSUE THREAD

**Issue by mikechambers610** [awslabs/aws-mobile-appsync-sdk-js#335]
EDIT : More Details 

I have created my file object out of a picture from Image-Picker in React-Native. Then I am attempting to send the username and file (picture) to AWS AppSync via S3ObjectInput.

When I send it, it should hit the resolver and be moved to the S3 public bucket and also be storing the url info in the S3Object in DynamoDB. When I execute the mutation. Nothing is happening. Any help would be greatly appreciated!

I've tried to share as much of my code as possible.

> AppSync Schema :

input CreateTestFileInput { 
  username: String! 
  file: S3ObjectInput! 
}

type TestFile { 
   username: String 
   file: S3Object 
} 

type S3Object { 
   bucket: String! 
   region: String! 
   key: String! 
}

input S3ObjectInput { 
   bucket: String! 
   region: String! 
   localUri: String 
   key: String 
   mimeType: String }

createTestFile(username: String!, file: S3ObjectInput!): TestFile

> React-Native code & mutation :

//I am taking the uri from ImagePicker and placing it in "uri" via result in state. Then turning the //uri into blob().

sendPicS3 = async () => {
let file;
let uri = this.state.result.uri;

//turn uri into blob
const imageData = await fetch(uri)
const blobData = await imageData.blob()

//take name and type from blobData
const fileName = blobData.data.name;
const mimeType = blobData.data.type;

if (uri) {
const { fileName, type: mimeType } = uri;
const [, , , extension] = /([^.]+)(.(\w+))?$/.exec(fileName);

const bucket = AWSConfig.aws_content_delivery_bucket;
const region = AWSConfig.aws_content_delivery_bucket_region;
const key = [uuidV4(), extension].filter(x => !!x).join('.');

file = {
 bucket,
 key,
 region,
 mimeType: blobData.data.type,
 localUri: blobData,
};

this.props.onCreateTestFile({
 username: this.state.username,
 file: file,
}) 

//console.log(file) = below output : 
// bucket: "my-bucket-layout-hidden"
// key: "my-key-hidden"
// localUri: Blob {_data: {…}}
// mimeType: "image/jpeg"
// region: "us-east-1"
} }

>Graph QL mutation for component above :
graphql(CreateTestFile, {
props: props => ({
onCreateTestFile: testfile => props.mutate({
variables: { testfile },
optimisticResponse: {
__typename: 'Mutation',
createTestFile: {
...testfile,
__typename: 'TestFile',

file: {
 __typename: 'S3Object',
 ...testfile.file,
   },
  }
 },
})
}) })

GraphQL-tag mutation :

import graphql from 'graphql-tag'

export default graphql`
   mutation CreateTestFile ($username: String!, $file: S3ObjectInput!){
   createTestFile( input: {username: $username, file: $file} )
{ 
   username 
   file 
} }

>AppSync Resolver :

{

"version": "2017-02-28",
"operation": "PutItem",
"key": {
   "id": $util.dynamodb.toDynamoDBJson($ctx.args.input.username),
},

set( $attribs = $util.dynamodb.toMapValues($ctx.args.input) )
set( $file = $ctx.args.input.file )
set( $attribs.file = $util.dynamodb.toS3Object($file.key, $file.bucket, $file.region) )

"attributeValues": $util.toJson($attribs)
}

> Credentials from App.js :

const client = new AWSAppSyncClient({
   url: AWSConfig.aws_appsync_graphqlEndpoint,
   region: AWSConfig.aws_appsync_region,
   auth: {
   type: AWSConfig.aws_appsync_authenticationType,
   jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken(),
},
   complexObjectsCredentials: () => Auth.currentCredentials(),
   dataIdFromObject: o => o.id,
}, {
   defaultOptions: {
   watchQuery: {
   fetchPolicy: 'cache-and-network',
}, }, });

Version :

"aws-amplify": "^0.2.9",
"aws-amplify-react-native": "^0.2.15",
"aws-appsync": "^1.3.4",
"aws-appsync-react": "^1.0.12",
"aws-sdk": "^2.247.1",
"expo": "^27.0.0",

Expect : S3 object to be created in the S3 public bucket and for the S3 object url to be stored in the DynamoDB record. Actual Result : No error outputs and nothing happens in AWS DynamoDB or S3.

**Comment by marsinearth** [comment]
I have similar issue. I have dealt with the appsync graphql s3ObjectInput not being uplaoded to S3 problem with setting up cognito & IAM policy but still on my S3 bucket the file size is always being 80 bytes, seemingly that the local url is literally set as a string `assets-library://blahBlah` and that's it. The downloaded file is not able to be opened either. I think the S3Object attr name 'localUri' makes me confused to assume that the Appsync client (AWSAppSyncClient) doesn't automatically pulls up the assets library file when it requests to the server.

**Comment by mikechambers610** [comment]
Hi - I was able to acheive my goal of uploading a picture to S3 and having a url to the S3 object in my dynamoDB. First I am sending the file to S3 via the NPM package 'react-native-aws3'. Once the file is uploaded to the bucket which I have used IAM to grant the cognito role permission, the url is returned as a promise. I then fire off a mutation to dynamodb to create an item in the table with the pic attribute as a String where I am storing the URL. Below code is working : 


sendPicS3 = async () => {

     //console.log(this.state.result)
     let file = {
     // `uri` can also be a file system path (i.e. file://)
     uri: this.state.result.uri,
     name: uuidV4()+"profpic.jpg",
     type: "image/png"
    }

    const config = {
      keyPrefix: "profPic/",
      bucket: AWSConfig.aws_resource_bucket_name,
      region: AWSConfig.aws_project_region,
      accessKey: AWSKeys.acckey,
      secretKey: AWSKeys.seckey,
      successActionStatus:201
    }
    console.log(config)

    RNS3.put(file, config).then(response => {
  if (response.status !== 201) {
    throw new Error("Failed to upload image to S3");
  } else{

    console.log(response)
      let id = this.state.backupusername
      let profPic = response.body.postResponse.location


     this.props.onUpdateMember({
        id: id,
        profPic: profPic,
      })

      this.setState({
        result: '',
        cancelled: "true",
        profPicChange: "false"
      })



  }
});


}

**Comment by marsinearth** [comment]
I am having a similar problem. I figured out the permission issue with correctly setting up Cognito user pool with federated identity and attaching a put/del S3 privilege IAM policy to the RN App user. However, on my S3 bucket the file info is correctly uploaded (which means that there is no auth issue), but the file size is only 80 bytes every time. After a few days of investigation, I found out the reason that actually the file has been treated as a string of the assets-library path, not the actual file which should be extracted from that path. I don't know how to solve it. Should've I put localUri attr of S3ObjectInput with the file Blob? Converting the image file unto base64 didn't work either..

**Comment by ChrisFieldsII** [comment]
Hello @marsinearth 

I was having the same problem and finally was able to get images to load into my S3 bucket!

I was using `react-native-camera`'s `takePictureAsync()` function to take pictures and then using the `data.uri` property of that taken photo as the `localUri`. This was putting pictures in S3 appropriately but all of them were corrupted. 

I then added the `RNFetchBlob` package and took the `data.uri` from the `react-native-camera` `takePictureAsync()` function and basically converted that file to a Buffer base64 encoded. I am using that string as the `localUri` for S3 uploads and it works fine. 

![schema](https://user-images.githubusercontent.com/38661015/53587537-3ee30a80-3b50-11e9-93c9-02c71fa1c20e.png)
![mutation](https://user-images.githubusercontent.com/38661015/53587536-3ee30a80-3b50-11e9-8e36-0fb75a487f3d.png)
![code](https://user-images.githubusercontent.com/38661015/53587677-92555880-3b50-11e9-9851-7802f57f47ef.png)

**Comment by jtaylor1989** [comment]
I struggled a lot in implementing file upload using Amplify, AppSync, and S3. Now reading all your answers and working on my own I thought it will be great to share my own solution.

I am using [Expo](https://docs.expo.io/versions/v28.0.0/sdk/camera/#__next) to access the library of the device, RNS3 to put the image in S3, and the AppSync SDK to execute the mutation that store the reference in DynamoDB.

Here are screenshots of my entire code. Keys are from your IAM user.

schema.graphql
<img width="667" alt="schema" src="https://user-images.githubusercontent.com/26605247/54024840-b76d4b00-4190-11e9-8a66-5d8f65c66a52.png">

Mutation
<img width="476" alt="mutation" src="https://user-images.githubusercontent.com/26605247/54024839-b76d4b00-4190-11e9-8e14-d9397acc370c.png">

App.js
<img width="666" alt="app" src="https://user-images.githubusercontent.com/26605247/54024836-b76d4b00-4190-11e9-8d07-ff2d9448acb0.png">

First half of the AddPhoto.js
<img width="669" alt="addphoto-1" src="https://user-images.githubusercontent.com/26605247/54024834-b6d4b480-4190-11e9-9c09-5f5892ee7b4e.png">

Second half of the AddPhoto.js
<img width="669" alt="addphoto-2" src="https://user-images.githubusercontent.com/26605247/54024835-b76d4b00-4190-11e9-8a50-4d235c0fee58.png">

<img width="670" alt="keys" src="https://user-images.githubusercontent.com/26605247/54024837-b76d4b00-4190-11e9-800a-9c435db3b606.png">

I tried getting rid of RNS3 by suing the [Storage](https://aws-amplify.github.io/docs/js/storage) API to put the image in S3 (goign fully Amplify), but the uploaded image is always broken .

**Comment by ChrisFieldsII** [comment]
Very nice. I'll have to check RNS3 out.

I had the same problem with images being uploaded to S3 being broken until I used `react-native-fetch-blob` to convert the image in the filesystem to base64.

**Comment by jtaylor1989** [comment]
Thanks.

In the previous versions of Amplify I had the following code working prefectly ( using `rn-fetch-blob`)

<img width="252" alt="Screenshot 2019-03-08 at 20 28 39" src="https://user-images.githubusercontent.com/26605247/54053946-cb409d80-41e0-11e9-8a52-25da5f1a2ea4.png">

version:

`"aws-amplify": "^1.1.7",
   "aws-amplify-react-native": "^2.0.7",
    "rn-fetch-blob": "^0.10.13"`

I did not need to use RNS3 at all.

However, the exact same code in the latest Amplify versions does not work. 

`"aws-amplify": "^1.1.19",
    "aws-amplify-react-native": "^2.1.7",`
