### ISSUE TITLE
aws appsync combine filter operators

### ISSUE THREAD

**Issue by rpostulart** [awslabs/aws-mobile-appsync-sdk-js#346]
Is it possible in AWS appsync / amplify to combine filter operators, like:

`
const filterInput = {

        or:[

          {
          and: [
                  {createdById: { eq: userID }},
                  {chatWithId: { eq: chatWithUser.id }}
                ]
          },
          {
          and:  [
                  {createdById: { eq: chatWithUser.id }},
                  {chatWithId: { eq: userID }}
                ]
          }
        ]
      }
`

Because for me this is not filtering / working as expected.

**Comment by manueliglesias** [comment]
Hi @rpostulart 

Yes, this is possible.

What is not working as expected?

**Comment by manueliglesias** [comment]
Is it working if you try a simple filter?

**Comment by ricardoribas** [comment]
Is not working for me either. If i do something like this:
`
or: {
      customId: {
        contains: "abcd"
      },
      customId:{
        contains: "defg"
      }
    }
`
i get only the results of the first filter always (even if i switch the order)

**Comment by olivier545** [comment]
Hi  @rpostulart @ricardoribas @manueliglesias 
I'm trying to achieve the same thing combining AND & OR filters in AppSync query.
Did you find a solution ? Could you please share ?
Thanks

**Comment by olivier545** [comment]
It works !
For those still trying, here is a working example :

query list {
    list (filter :{
    and: [
    { available: {eq: true}},
    { id: {eq: "XXXXX"}}, 
    {
    or: [
      {promo: {eq: true}},
      {price: {between : [40,45] }}
    ]
    }
    ]}
)
{
      items {
        id
        price
      }
    }
  }

**Comment by rpostulart** [comment]
With this example we can close this issue

**Comment by jdanielsyeah** [comment]
When using the AppSync console, using the Query builder doesn't generate a useable code:
<img width="106" alt="image" src="https://user-images.githubusercontent.com/109956937/200547917-bd6fc820-ba59-4ebd-a5e3-d73069f6f272.png">

For example, clicking the 'or' option and then providing a value 'myName' for the 'name' field generates this:
``` graphql
query MyQuery {
  listInputSchemas(filter: {or: {name: {eq: "myName"}}}) {
    items {
      id
      name
    }
  }
}
```

It takes a bit of working out from here that you should wrap the `{name: {eq: "myName"}` section in square [] brackets. It would be useful if the [] were generated and with new lines/indentation to make it more obvious what the intention is.
