### ISSUE TITLE
Loosen dependency of apollo-client

### ISSUE THREAD

**Issue by stephankaag** [awslabs/aws-mobile-appsync-sdk-js#348]
The version of apollo-client is currently frozen at 2.4.6. The latest release available is 2.4.12 and multiple important fixes have happened in the meantime. Does it make sense to loosen the requirement somewhat? I can create a pull request if desired.

https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/2278942104ca96aead029075461ae554dc4a0408/packages/aws-appsync/package.json#L24

**Comment by undefobj** [comment]
We used to not have a specific version pinned but there were breaking changes in Apollo that didn't come from major version releases, and unfortunately that broke customers. Therefore we have the version pinned and if there is missing functionality we instead will evaluate on a case by case basis upgrading with thorough testing.

If there are specific features from newer releases you are looking for could you please open issues for them and we can evaluate?

**Comment by stephankaag** [comment]
That makes sense. Thanks for your clarification.

**Comment by ffxsam** [comment]
This is causing TypeScript errors. #362
