### ISSUE TITLE
Example for custom loading component on Rehydrated Component!

### ISSUE THREAD

**Issue by lolcoolkat** [awslabs/aws-mobile-appsync-sdk-js#35]
Could someone please share an example for how to add a custom loading component to the <Rehydrated> component with render props! thanks

**Comment by manueliglesias** [comment]
I @lolcoolkat , let me know if this works for you:

```javascript
const WithProvider = () => (
  <ApolloProvider client={client}>
    <Rehydrated render={({ rehydrated }) => (
      rehydrated ? <App /> : <strong>I am loading...</strong>
    )}>
    </Rehydrated>
  </ApolloProvider>
);

export default WithProvider;
```

**Comment by lolcoolkat** [comment]
@manueliglesias no it does not. It still just flashes "Loading..." on the screen and then the screen goes white. I even upgraded to the latest version too.. not sure what the issue is.

**Comment by lolcoolkat** [comment]
Nvm @manueliglesias works now ... :D Thank you!
