### ISSUE TITLE
Subscriptions are rejected by the server (InvalidSignatureException)

### ISSUE THREAD

**Issue by greimela** [awslabs/aws-mobile-appsync-sdk-js#353]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When using subscriptions with control events enabled (`{'@@controlEvents': true}`) together with IAM based authentication, the AppSync server rejects all requests with a `403 InvalidSignatureException`.

The root cause seems to be that the signature created by the auth-link includes the `@@controlEvents` key but the subscription-handshake-link removes that key before sending the request to the server.
Therefore request and signature do not match.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Initialize AppSync client with IAM based authentication
2. Create subscription using `client.subscribe()` with variables `{'@@controlEvents': true}` or `client.sync()` (uses control events internally as well)

**What is the expected behavior?**
The signature should match the request and should be accepted by the server.

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**
1.7.1 in the browser.

**Comment by greimela** [comment]
I already provided a possible fix in #347, but there might be a better solution.

**Comment by manueliglesias** [comment]
Thank you for the contribution @greimela 
The PR has been approved. It should be merged and published later this week.
