### ISSUE TITLE
Subscription batching

### ISSUE THREAD

**Issue by sis-dk** [awslabs/aws-mobile-appsync-sdk-js#357]
**Do you want to request a *feature* or report a *bug*?**
> Ask a question.

**What is the current behavior?**
> I have 8 subscriptions that are subscribed when app boots. I loop through all the subscriptions and call these functions in each loop
```
var handler = client.subscribe({
  query,
  variables
})

handler.subscribe({
  next: () => {},
  error: () => {}
})
```

**What is the expected behavior?**
> Is there a way I can avoid multiple calls and subscribe to all subscriptions in one go. Something like
```
var handlers = client.subscribe([
  {
    query,
    variables
  },
  {
    query,
    variables
  }
])
```

**Comment by manueliglesias** [comment]
Hi @sis-dk 

You can try something like this:

```graphql
subscription MultiSubs($event1: String! $event2: String!) {
  sub1: subscribeToEventComments(eventId: $event1) {
    eventId
    commentId
    content
  }
  sub2: subscribeToEventComments(eventId: $event2) {
    eventId
    commentId
    content
  }
}
```
and then

```js
const variables = {
  "event1": "aaaa",
  "event2": "bbbb"
};

var handlers = client.subscribe([
  {
    query,
    variables
  },
])
```
