### ISSUE TITLE
DeltaSync Errors with ModelConnections

### ISSUE THREAD

**Issue by ChrisFieldsII** [awslabs/aws-mobile-appsync-sdk-js#374]
>  Note: If your issue/feature-request/question is regarding the AWS AppSync service, please log it in the 
  [official AWS AppSync forum](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0)

**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Using the deltaSync process on a model that returns a ModelConnection seems to break some of the logic in the deltaSync file. This is due to the array that the logic is trying to access being embedded within the items property.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In order to reproduce, use the deltaSync process on a query that returns a ModelConnection. writeCacheUpdates should error right away at result.forEach. Additional errors occur where an array is expected but really an object is provided (the array is within the items property of this object). I am attaching pictures of the errors stopped at debug breakpoints. NOTE! The first picture is caused by a subscription triggering which requires different logic as a ModelConnection isn't returned!
![subscriptionbreaksMyChanges](https://user-images.githubusercontent.com/30332608/54626903-29228000-4a40-11e9-8344-5e3c1267714d.png)
![baseResult_Items](https://user-images.githubusercontent.com/30332608/54626904-29228000-4a40-11e9-80f5-eb020134cd2e.png)
![baseResult_slice](https://user-images.githubusercontent.com/30332608/54626905-29228000-4a40-11e9-8a28-260f066789b2.png)
![baseResult_notArray](https://user-images.githubusercontent.com/30332608/54626906-29bb1680-4a40-11e9-9a4d-c29de6e6ffd9.png)
![cacheUpdates_error](https://user-images.githubusercontent.com/30332608/54626908-29bb1680-4a40-11e9-80af-4141e6abc1b4.png)

**What is the expected behavior?**
The deltaSync process accounts for ModelConnection types. I modified the deltaSync file a bit to work for me. The modifications are commented with "MODIFIED BY ME". I am attaching that file too.
[deltaSync.txt](https://github.com/awslabs/aws-mobile-appsync-sdk-js/files/2984634/deltaSync.txt)

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**

  React Native Environment Info:
    System:
      OS: macOS 10.14.3
      CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
      Memory: 2.01 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.12.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.7.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.2 => 16.8.2 
      react-native: 0.58.4 => 0.58.4 

"dependencies": {
    "aws-amplify": "^1.1.19",
    "aws-amplify-react": "^2.3.0",
    "aws-amplify-react-native": "^2.1.7",
    "aws-appsync": "^1.7.2",
    "aws-appsync-react": "^1.2.6",
    "graphql-tag": "^2.10.1",
    "react": "^16.8.2",
    "react-apollo": "^2.4.1",
    "react-native": "0.58.4",
    "reactn": "^0.2.2",
  }

**Comment by manueliglesias** [comment]
Hi @ChrisFieldsII 

Are you using the  `buildSync` helper? If so, it comes with some requirements:

> Requirements for helper function
> - Your baseQuery returns a list, not a nested type

https://aws-amplify.github.io/docs/js/api#delta-sync

If you want to / need to use ModelConnections, you need to provide your own options to `client.sync`

**Comment by ChrisFieldsII** [comment]
Hello @manueliglesias ,

Yes I am using the buildSync helper. I obviously didn't pay enough attention to that documentation, thanks! This makes sense now that I think about it. Closing.
