### ISSUE TITLE
correctClockSkew

### ISSUE THREAD

**Issue by mcarriere** [awslabs/aws-mobile-appsync-sdk-js#385]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
When using Cognito, HTTP 403 with Signature expired: XXX is now earlier than XXX (XXX - 5 min.)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Change your clock manually by over 5 minutes in the past or future.

**What is the expected behavior?**
on the aws-sdk there is an option for correctClockSkew (https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/APIGateway.html, https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/AppSync.html).

The main goal on this is that when some machine has a clock that for some reason is not correctly synchronized, the user will still able to make a request.

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**
browser

**Comment by manueliglesias** [comment]
Hi @mcarriere 

Please create an issue in the [amplify repo](https://github.com/aws-amplify/amplify-js)

**Comment by kevinsperrine** [comment]
@manueliglesias I've been digging into this issue for a little while now and I'm trying to understand why you redirected it to Amplify. As best I can tell, the authLink is only using the access keys and session tokens, but then signs them using the Signer in the appsync-sdk without any connection to Amplify.

Couldn't we fix the incorrect clock skew errors with AppSync (https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/master/packages/aws-appsync/src/link/auth-link.ts#L99, https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/master/packages/aws-appsync/src/link/signer/signer.ts#L219) by having the signer adjust the datetime using the AWS.config.systemClockOffset from the JS SDK? https://github.com/aws/aws-sdk-js/blob/38bf84c144281f696768e8c64500f2847fe6f298/lib/event_listeners.js#L370 and https://github.com/aws/aws-sdk-js/blob/38bf84c144281f696768e8c64500f2847fe6f298/lib/util.js#L763

**Comment by EnanlyPay** [comment]
> @manueliglesias I've been digging into this issue for a little while now and I'm trying to understand why you redirected it to Amplify. As best I can tell, the authLink is only using the access keys and session tokens, but then signs them using the Signer in the appsync-sdk without any connection to Amplify.
> 
> Couldn't we fix the incorrect clock skew errors with AppSync (https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/master/packages/aws-appsync/src/link/auth-link.ts#L99, https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/master/packages/aws-appsync/src/link/signer/signer.ts#L219) by having the signer adjust the datetime using the AWS.config.systemClockOffset from the JS SDK? https://github.com/aws/aws-sdk-js/blob/38bf84c144281f696768e8c64500f2847fe6f298/lib/event_listeners.js#L370 and https://github.com/aws/aws-sdk-js/blob/38bf84c144281f696768e8c64500f2847fe6f298/lib/util.js#L763

Hi @kevinsperrine I tried your fix but it didn't work with appsync. I'm still getting 403 errors. Is it possible to make it work without using apollo (only aws-appsync) ?

**Comment by 112Cracker** [comment]
Why this issue is closed? (where could I find a solution to this issue?) We experience the same problem when trying to fire a mutation call using appsync.AWSAppSyncClient

**Comment by KevinToala** [comment]
Hi,

I have the same issue. I use Aws appsync sdk for my angular project with AUTH_TYPE.AWS_IAM
How to solve this issue? :(
