### ISSUE TITLE
update mutation pending on lambda

### ISSUE THREAD

**Issue by sessaidi** [awslabs/aws-mobile-appsync-sdk-js#409]
>  Note: If your issue/feature-request/question is regarding the AWS AppSync service, please log it in the 
  [official AWS AppSync forum](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0)

**Do you want to request a *feature* or report a *bug*?**
 bug

**What is the current behavior?**
When I make this mutation from a lambda, this one will just hanged and not finish, the lambda will just throw a timeout error, but no errors in the logs.

configuration AWS
```typescript
AWS.config.update({
    region: <region>,
    credentials: new AWS.Credentials({
        accessKeyId: <id>,
        secretAccessKey: <secret>
    })
});

```

client:
```typescript
const client: any = new AWSAppSyncClient(<any>{
	url: <url>,
	region: <region>,
	auth: {
		type: AUTH_TYPE.AWS_IAM,
		credentials
	},
	disableOffline: true
});
```

```typescript
const trigger = gql`mutation notification($id: String!, $link: String!) {
	triggerMe(input: { id: $id, link: $link }) {
		id
		link
	}
}`;
```

mutation
```typescript
const response: any = await client.mutate({
	mutation: triggerMe, 
	variables: { id: "1", link: "localhost" },
	fetchPolicy: 'no-cache' //still not working without
});
```

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**
lambda - nodejs8.10 and nodejs10.x 
latest version of aws-appsync

this code worked before, but I don't know why, but the same code doesn't work anymore,
this issue is quite similar to this one https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/351#issue-406101764

**Comment by genesst** [comment]
@sessaidi Did you manage to fix this?
