### ISSUE TITLE
Error transforming the velocity template

### ISSUE THREAD

**Issue by lolcoolkat** [awslabs/aws-mobile-appsync-sdk-js#41]
Anyone know what this error is referring to?
https://github.com/serverless/serverless-graphql/issues/311

Thanks for any help!

**Note**: Figured I would also post here since this is where AppSync is managed!

**Comment by undefobj** [comment]
Can you post the schema as well as the request and response templates from the resolver?

**Comment by lolcoolkat** [comment]
So I figured out the issue @undefobj ...

It was due to the fact that it was trying to Query a record in the table that didn't exist. But i'm not sure why that would cause it to return a mappingtemplate erorr instead of just like data: null or something like that?

**Comment by undefobj** [comment]
Can you share the query template and database structure?

**Comment by howdyhyber** [comment]
I also encountered this error, this is the schema

type Vehicle{
   vehicle_id:ID!
   vehicle_name:String
   plate_number:String
}

type Driver{
   driver_id:ID!
   driver_name:String
   vehicle:Vehicle
}

Then if i query all drivers with no vehicle, it will error something like this.

{
      "path": [
        "drivers",
        1,
        "vehicle"
      ],
      "data": null,
      "errorType": "MappingTemplate",
      "errorInfo": null,
      "locations": [
        {
          "line": 14,
          "column": 7,
          "sourceName": null
        }
      ],
      "message": "Error transforming the velocity template"
    }

How to solve this problem?

**Comment by JouiiinO** [comment]
Got the same issue for one of my AppSync, any idea or thoughts about where it could come from ?
