### ISSUE TITLE
Storage.get not working with the Connect Component and unable to be used with arrays

### ISSUE THREAD

**Issue by codingforsuckers** [awslabs/aws-mobile-appsync-sdk-js#413]
Here is what my application looks like. There's a dynamo db table which stores Records and some f this records are S3Objects mainly audio and image files. Which is all good. Now when a user adds a new record he is supposed to see it emmediately which is done using subscription and the connect component and this is where the problem lies. When I putin say an image file its uploaded and emmediately returned but when I put in an audio file its not being returned. Now I believe the reason this is happening is because with images I use `<S3Image/> `but there is nothing similar being offered for audios by amplify. So for the audios I use Storage.get. I tried 2 main scenarios.

Scenario 1
I made the storage.get call within the connect component but here I encountered 2 problems on onehand I couldn't pass in the keys returned from the API call and on the otherhand I couldnot access the result of Storage.get I could only console.log it. here is the code:

```
<Connect
        query={graphqlOperation(listRecordss)}
        subscription={graphqlOperation(onCreateRecords)}
        onSubscriptionMsg={onNewRecord}
    >
    
        {({data, loading, error}) => {
            if (loading) return "Loading"
            if (error) return "Error"
            const ListRecord = data.listRecordss.items
            console.log('ListRecord', ListRecord)
            const k = ListRecord.map((rest) => (rest.audio.key
           )))
          
          Storage.get(this.state.voice)
        .then(result =>{ console.log("Storageb");
         const Aud = result;
         console.log("Storageb", Aud)
         this.setState({Aud})
        })
        .catch(err => console.log(err))
            
            return <div><MUIDataTable
            title={"Leistungen"}
            data={ ListRecord.map((rest) => (
              [rest.createdAt, rest.record, 
                 <audio
           accept="audio/*"
            ref={c => {
              this.audioSource = c;
            }}
            controls="controls"
            src={this.state.Aud}
            id="simple-modal-description"
          >
          </audio>, 

            <Image p={rest.file.key}/>,
                rest.arzt, rest.patient]
           ))}
            columns={columns}
            options={options}
            />
            </div>
            
        }}
    </Connect>

```
Scenario2:
This time around I created a new class `<AudioClass/>` then I passed the keys returned by my query into this class. Within `<AudioClass/>` I put the Storage.get within A function and passed keys as props into storage.get which then worked in the sense that it returned my audios. But it came with its own problems since now when I added a record the audio section would not change which led to lots of data being in the wrong position.(Ps I imported `AudioClass` into the class above in the area with the `<audio>`).  

AudioClass:
```

state = {
        Audio: [],
      };

   componentDidMount() {
        Storage.get(this.props.a)
              .then(result =>{ console.log("Storageb");
               const Me = result;
               this.setState({Audio: Me})
               //console.log("geb", Me)
              })
              .catch(err => console.log(err))
            
    }

  render() {
    //console.log("no", this.props.a)
    return (
        <div>
         <audio
           accept="audio/*"
            ref={c => {
              this.audioSource = c;
            }}
            controls="controls"
            src={this.state.Audio}
            id="simple-modal-description"
          >
          </audio>

          
          
        </div>
    );
  }
}
```
So deos anyone know how I can resolve this or is there some `<S3Audio/>` I have never heard of? Thanksalot for any hep.
```

**Comment by elorzafe** [comment]
@codingforsuckers this is issue is related to AWS Amplify, I will close this issue but feel free to ask it on [AWS Amplify repo](https://github.com/aws-amplify/amplify-js/)
