### ISSUE TITLE
Publish a working version for RN >= 0.60 users

### ISSUE THREAD

**Issue by usmansbk** [awslabs/aws-mobile-appsync-sdk-js#445]
**Do you want to request a *feature* or report a *bug*?**
Publish a version with `NetInfo` fixed for RN >= 0.60

**What is the current behavior?**
App crash due to `aws-appsync-react`  `Rehydrated` component and `aws-appsync` using deprecated `NetInfo`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
`react-native run-android` any project using `aws-appsync` and `aws-appsync-react`

**What is the expected behavior?**
use new `@react-native-community/netinfo` for rehydrated component and update `aws-appsync` `package.json` to use `@redux-offline/redux-offline:  "2.5.2-native.0"`

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**

> System:
>     OS: Windows 10
>     CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz 
>     Memory: 1.92 GB / 7.90 GB
> Binaries:
>     Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
>     Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
>     npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
IDEs:
>     Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

**Comment by felixchan** [comment]
Agree

**Comment by bernhardt1** [comment]
has anyone implemented a workaround ?

I don't want to wait for a release to upgrade to 0.60.+

**Comment by amie-wilt** [comment]
See this comment: https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/443#issuecomment-515574105

**Comment by manueliglesias** [comment]
Updated posted at https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/443#issuecomment-516140486

**Comment by Ashish5591** [comment]
Hi, 
We have just released an unstable version that addresses this issue. More details here: https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/443#issuecomment-519310531
