### ISSUE TITLE
Add CHANGELOG entries for 2.0.0

### ISSUE THREAD

**Issue by nirvdrum** [awslabs/aws-mobile-appsync-sdk-js#463]
Both the `aws-appsync` and `aws-appsync-react` packages had major releases (2.0.0) a little over a week ago. However, neither package's CHANGELOG files have been updated to note the release and indicate what has changed. It would be very helpful to both note what has changed and any considerations necessary when upgrading from the 1.x.y (on even 1.8.y) releases.

**Comment by Ashish5591** [comment]
@nirvdrum The  CHANGELOG has been updated with entries for the 2.0.0 release. 

Also the README was previously updated with important considerations and instructions for major changes that were part of this release, eg. support for RN 0.60
