### ISSUE TITLE
Error: GraphQL error: Variable 'input' has coerced Null value for NonNull type 'CreateCaseInput!'

### ISSUE THREAD

**Issue by norby3** [awslabs/aws-mobile-appsync-sdk-js#464]
**Do you want to request a *feature* or report a *bug*?**
Question - sorry for the question here but the AppSync team folks seem to check in here. 

**What is the current behavior?**
I need help configuring the High Order Component with the amplify codegen code.  Have not been able to get past the error message in the title of this issue.  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
amplify add codegen --apiId nhn....

**What is the expected behavior?**
Pass data from a input form to the GraphQL service on AWS AppSync 

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**
Here are my react-native dependencies - arrived it this after several weeks of trial and error and help from @Ashish5591 @undefobj  and others.  

```javascript
  "dependencies": {
    "@react-native-community/netinfo": "^4.2.1",
    "apollo-client": "^2.6.4",
    "aws-appsync": "^2.0.0",
    "aws-appsync-react": "^2.0.0",
    "axios": "^0.19.0",
    "graphql": "^14.5.5",
    "graphql-tag": "^2.10.1",
    "react": "16.8.6",
    "react-apollo": "2.5.8",
    "react-dom": "^16.9.0",
    "react-native": "0.60.5",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-image-crop-picker": "^0.25.2",
    "react-native-maps": "^0.25.0",
    "react-native-scalable-image": "^1.0.0",
    "react-native-screens": "^2.0.0-alpha.3",
    "react-navigation": "^4.0.4",
    "react-navigation-stack": "^1.7.3",
    "uuid": "^3.3.3"
  },
```

I used the AWS AppSync console to define the model called 'Case'.  Can run a query from the react-native app and am able to list the contents of Case.  But can't figure out how to configure the mutation. 

From the amplify codegen file src/graphql/mutations.js  

```javascript
/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const createCase = `mutation CreateCase($input: CreateCaseInput!) {
  createCase(input: $input) {
    uuid
    caseType
    caseVersion
    status
    createdAt
    updatedAt
    createdByUser
    createdByGroup
    reports
    boards
    groups
  }
}
`;
```

The following is from my react native screen component - a form for creating a 'Case'.  

```javascript 
  handleNext = () => {
 
    let rpt = this.createHotlineReportObj();
    let acase = this.createCaseObj(rpt);
    console.log(`handleNext case = ${JSON.stringify(acase)}`);

    //this.props.onAdd({ ...acase, uuid: acase.uuid });
    //this.props.onAdd( acase );
    this.props.onAdd({...acase});

    this.props.navigation.navigate('Tags');
  }
```

With the following code, just trying to wire up a mutation - at this point not concerned with optimistic response.  When testing with the ios simulator, it throws this error: 

> Error: GraphQL error: Variable 'input' has coerced Null value for NonNull type 'CreateCaseInput!'

```javascript
export default compose(
  graphql(gql(createCase), {
    options: {
      errorPolicy: 'ignore'
    },
    props: props => ({
      onAdd: input => props.mutate({
          variables: input
      })
    })
  }),
)(Photos);
```

Not sure, but am guessing that the problem is something to do with these three lines: 
```javascript 
    props: props => ({
      onAdd: input => props.mutate({
          variables: input
      })
    })
```

Is there a working example somewhere on the proper way to pass in the input data to the mutation?   

I've read every Nader Dabit @dabit3 tutorial and/or video and code samples from @Ashish5591, @undefobj, @manueliglesias  etc   Can't find the trick to get past this prob. 

I am specifically trying to get this react-native app working with AWS AppSync SDK because of the offline and caching features.   

Have seen the bug on the aws-amplify board - not sure if these issues are related - think that user @lahirian was using different client lib.  
[https://github.com/aws-amplify/amplify-cli/issues/327](url)  

Here is the full error message: 
```
Possible Unhandled Promise Rejection (id: 0):
Error: GraphQL error: Variable 'input' has coerced Null value for NonNull type 'CreateCaseInput!'
Error: GraphQL error: Variable 'input' has coerced Null value for NonNull type 'CreateCaseInput!'
    at new ApolloError (blob:http://localhost:8081/e1d0376b-d27b-45a3-be43-872eccb7d7da:123433:28)
    at Object.next (blob:http://localhost:8081/e1d0376b-d27b-45a3-be43-872eccb7d7da:124554:25)
    at notifySubscription (blob:http://localhost:8081/e1d0376b-d27b-45a3-be43-872eccb7d7da:118268:20)
    at onNotify (blob:http://localhost:8081/e1d0376b-d27b-45a3-be43-872eccb7d7da:118312:5)
    at SubscriptionObserver.next (blob:http://localhost:8081/e1d0376b-d27b-45a3-be43-872eccb7d7da:118362:9)
    at notifySubscription (blob:http://localhost:8081/e1d0376b-d27b-45a3-be43-872eccb7d7da:118268:20)
    at onNotify (blob:http://localhost:8081/e1d0376b-d27b-45a3-be43-872eccb7d7da:118312:5)
    at SubscriptionObserver.next (blob:http://localhost:8081/e1d0376b-d27b-45a3-be43-872eccb7d7da:118362:9)
    at Object.next (blob:http://localhost:8081/e1d0376b-d27b-45a3-be43-872eccb7d7da:183306:30)
    at notifySubscription (blob:http://localhost:8081/e1d0376b-d27b-45a3-be43-872eccb7d7da:118268:20)
```

**Comment by norby3** [comment]
If anybody else has this problem, I *think* the fix is to invoke like this:

```javascript 
this.props.onAdd({input: acase});
```

In the original code below, you can see my several attempts to get the format correct.   Three of them are commented out.  There are many other embarrassing tries not shown.  :-0 
  
```javascript 
  handleNext = () => {
    //this.save();
    let rpt = this.createHotlineReportObj();
    let acase = this.createCaseObj(rpt);
    console.log(`handleNext case = ${JSON.stringify(acase)}`);

    //this.props.onAdd({ ...cse, uuid: cse.uuid });
    //this.props.onAdd( cse );
    //this.props.onAdd({...acase});
    this.props.onAdd({input: acase});

    this.props.navigation.navigate('Tags');
  }
```

Self criticism:  they say "every pain is an opportunity to learn."  I was trying to get this done without reading all the Apollo documentation.  Got motivated to go thru the Apollo tutorials (still in progress) gave me the idea to try the above.   [https://www.apollographql.com/docs/tutorial/introduction/](url)

**Comment by jvelonis** [comment]
For any other GraphQL n00bs like me, this error can also be caused by the mutation variable name not matching the actual argument name.  It doesn't help that all the GraphQL examples seem to declare the variable in two places, once with a $ prefix and once without, [for example](https://www.apollographql.com/docs/angular/basics/services/#mutation)
```
mutation upvotePost($postId: Int!) {
    upvotePost(postId: $postId) {
        id
        votes
    }
}
```
I assumed that the argument name should match the outer declaration ("$postId"), but apparently it should match the inner one ("postId").

**Comment by vrajgangani** [comment]
Make sure you pass all the required fields , which you have mention in scheme.graphql
