### ISSUE TITLE
TypeScript definitions for aws-appsync

### ISSUE THREAD

**Issue by buggy** [awslabs/aws-mobile-appsync-sdk-js#48]
It would be really helpful to have Typescript definitions for aws-appsync. There seem to be three options.

1. Maintain them separately in DefinitelyTyped.
2. Manually maintain them (I'll submit a PR to do this for now)
3. Convert the package to TypeScript and automatically generate them. This might be an option because TypeScript is already being used to compile the JavaScript so the tooling is in place.

**Comment by dguisinger** [comment]
+1 ... driving me crazy not having typescript definitions

**Comment by muhajirframe** [comment]
+1

**Comment by Lyon22** [comment]
+1

**Comment by tgorka** [comment]
+1

**Comment by pablitodeveloper** [comment]
++1

**Comment by rhussmann** [comment]
Please add the Typescript types. It would be a great benefit to Typescript devs.

**Comment by vineethsoma** [comment]
+1

**Comment by manueliglesias** [comment]
Closed by #155

**Comment by buggy** [comment]
@manueliglesias  I finally had a chance to update my app and test this today. It worked great. Thank You!!
