### ISSUE TITLE
cleanup cache after user logs out

### ISSUE THREAD

**Issue by sid88in** [awslabs/aws-mobile-appsync-sdk-js#49]
trying to figure out how can we clean up cached data at client end once user logs out (aws-amplify). 

I found that if the fetchPolicy is cache and network and multiple users log-in then the data at the client end remains static (from the cache). One solution is to use 'network only' but not the best solution I gues?

**Comment by undefobj** [comment]
We have a roadmap item to add configurable cache controls to the client in the future. For now you will need to manage this from application code. On web this will be via local storage and on React Native it will be with AsyncStorage.

**Comment by sid88in** [comment]
thanks @undefobj ;)

**Comment by manueliglesias** [comment]
Hey @sid88in 

With aws-amplify@latest and aws-appsync@latest you should be able to do something like this to clear the cache on login: (you could adapt this to do it on logout, but the idea would be the same: call **`client.resetStore()`**)

```javascript
class App extends Component {
  state = {
    cleared: false
  }

  async componentWillMount() {
    client.onResetStore(() => this.setState({ cleared: true }));
    client.initQueryManager();
    await client.resetStore();
  }

  render() {
    const { cleared } = this.state;

    return !cleared ? (<div>Clearing cache</div>) : (
      <div className="App">
        {/* MyStuff */}
      </div>
    );
  }
}

const AppWithAuth = withAuthenticator(App, true);

export default () => (
  <ApolloProvider client={client}>
    <Rehydrated>
      <AppWithAuth />
    </Rehydrated>
  </ApolloProvider>
);
```

**Comment by mikechambers610** [comment]
This doesn't seem to fix the problem in react native.

If a user signs out and then signs in using a different account the previous user's data is still loaded and not the new user.

Is there really no way around this as of now? :(

**Comment by paalex** [comment]
That's a major security and usability issue. Did anyone manage to solve this?

**Comment by kkushimoto** [comment]
Is there any update for React Native?

**Comment by HashCode55** [comment]
Any update on this?

**Comment by MichaelHuy** [comment]
On React Native, await AsyncStorage.clear() working fine on my test.

**Comment by subnaik15** [comment]
How do i use in android 

i have tried this but getting an error: Could not create an instance 

 

> AWSAppSyncClient.builder()
>                 .context(syncPort.androidContext())
>                 .awsConfiguration(AWSConfiguration(syncPort.androidContext()))
>                 .build().clearCaches(
>                     ClearCacheOptions.builder()
> //                        .clearQueries()
> //                        .clearMutations()
>                         .clearSubscriptions()
>                         .build())
>         }
