### ISSUE TITLE
operation/context headers are new realtime subscription link during a subscription start

### ISSUE THREAD

**Issue by bitfrost** [awslabs/aws-mobile-appsync-sdk-js#496]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
headers set on an operation context by another apollo-link  are not forwarded during subscription start operation.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create and add a link to your apollo client:

const setDummyHeader = setContext(async (_, previousContext) => {
  const { headers } = previousContext;

    return {
        headers: {
          ...headers,
          Blah: `blah`
        }
      };
});

Note it will not be present during a subscription start operation.

**What is the expected behavior?**
Custom set in another link are honored and forwarded if not overwritten directly by this link.
With out this change we cannot use an attached datasource (to a subscription) to apply subcription logic.  Witt the legacy variant we can apply things like custom auth...
**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**
All.  This effects the new real time link, the mttq, legacy one does not have this problem.

**Comment by bitfrost** [comment]
raised https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/497 as a fix

**Comment by elorzafe** [comment]
Thanks bitfrost I merged that PR already, we will publish this on latest soon.
