### ISSUE TITLE
Query Batching? 

### ISSUE THREAD

**Issue by adamjv90** [awslabs/aws-mobile-appsync-sdk-js#52]
It looks like there is no way of supporting query batching since package.json doesn't include [apollo-link-batch-http](https://www.apollographql.com/docs/link/links/batch-http.html). Are there any plans to support this feature?

**Comment by RPDeshaies** [comment]
I don't really understand the point of using AppSync if it doesn't supports query batching. That's like one of the main benefit of using GraphQL

**Comment by manueliglesias** [comment]
Hi @adamjv90 , @RPDeshaies 

There are two similar concepts/approaches for this
- "Query *merging*"
- "Query *batching*" (transport level batching)

Query Batching is not yet part of the GraphQL standard/spec, the link you are referring to ([apollo-link-batch-http](https://www.apollographql.com/docs/link/links/batch-http.html)) relies on server support for that implementation (apollo-server)

AWS AppSync definitively supports Query *merging*, e.g.

```graphql
query {
  one: listEvents {
    items {
      name
    }
  }
  two: listEvents {
    items {
      description
    }
  }
}
```

**Comment by adamjv90** [comment]
Thanks @manueliglesias the solution you propose would work however it would require you to program your application queries in a single query managed through a single container component (react scenario). It would be excellent if appsync could support query batching in a way that would allow a bunch of smaller components needing only a little bit of data each to all roll up into a single batched query to your backend thus improving the performance of your application. 

Think of a list view where each row needed some data. Instead of having to code a list view container that would need to be responsible for figuring out which data its rows need, each row would be responsible for composing its own query and your application would batch up all the queries needed into a single request to your grapql server. This really seems like a very trivial problem that graphql and appsync should be able to solve.

**Comment by RPDeshaies** [comment]
@manueliglesias You are right. AppSync supports query merging, but as @adamjv90 described query batching is IMO way more efficient way of working and one of the great benefit of using an Appolo server VS AppSync.

Why close the issue? Because you are not going to implement it?

In that case, we might replace our Appsync server with a NodeJS lamda using Appolo concerning how much gain we might be able to get from query batching

**Comment by undefobj** [comment]
@adamjv90 @RPDeshaies thanks for the feedback. We'll definitely add to our backlog. At this time as @manueliglesias said this is not part of the GraphQL specification and as an AWS service we need to be very careful about implementation for backwards compatibility reasons on future changes. Perhaps I could recommend opening up an issue on the GraphQL repo (https://github.com/facebook/graphql) for this to be adopted into the spec faster?

In the meantime, we have implemented a batch feature for DynamoDB resolvers which is spec compliant and highly scalable, which may or may not help with your use case: https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-batch.html

**Comment by andrejunges** [comment]
@undefobj   are there any updates about the support of batch operations? (something that'd work similar as apollo-link-batch-http)
