### ISSUE TITLE
Pinned GraphQL dependency (v0.13)

### ISSUE THREAD

**Issue by kamilkisiela** [awslabs/aws-mobile-appsync-sdk-js#545]
Pinning a version of GraphQL and keeping it in `"dependencies"` makes it impossible to use with other tools and packages, especially when trying to use different versions of `graphql`.

GraphQL-JS is super sensible about `instanceof` usage and in most cases breaks if there are multiple `graphql` packages installed in one repository.

Here's my attempt to use the next version of `graphql-tools` https://github.com/aws-amplify/amplify-cli/pull/3836. E2E fails because of the problem I mentioned.

**Comment by evcodes** [comment]
Closing this issue as @manueliglesias's merged PR addresses this problem
