### ISSUE TITLE
Need more details on how complex objects work

### ISSUE THREAD

**Issue by ffxsam** [awslabs/aws-mobile-appsync-sdk-js#61]
Regarding:
https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-react.html#complex-objects

How does this work exactly? I don't understand what value `localUri` should be. When you select files to upload, `FileList` contains a list of `File` objects, which do not expose the full path of the file, just the names. It would make more sense to pass the `File` object to AWS AppSync which would then use `FileReader` to get an array buffer to pass to `s3.upload`.

Could someone give more details on how this works? Thanks!

**Comment by manueliglesias** [comment]
Answered in #63
