### ISSUE TITLE
Angular / NativeScript support

### ISSUE THREAD

**Issue by fhackenb** [awslabs/aws-mobile-appsync-sdk-js#64]
I'm working on a mobile app in NativeScript and Angular and would love to be able to use AppSync, especially for its offline capabilities. 

I've been trying to follow a tutorial for Node [https://docs.aws.amazon.com/appsync/latest/devguide/building-a-client-app-javascript.html](url) in the hopes that it could work, but haven't gotten a variety of errors and haven't gotten it working yet. 

I know you have on your site that you're planning to have an Angular / Ionic demo coming soon. Any idea when that might be? 

A NativeScript-specific integration would also be awesome

**Comment by goldenbearkin** [comment]
any update?

**Comment by jeremyputeaux** [comment]
I'm currently trying appsync with angular and I have few bugs. When can we expect just a sample?

**Comment by kwoxford** [comment]
How about it?

**Comment by undefobj** [comment]
Hello - We have an end to end sample written in Angular here: https://github.com/aws-samples/aws-mobile-appsync-chat-starter-angular

**Comment by demetrio812** [comment]
@undefobj So from the fact you closed the issue I can deduct you aren't going to support nativescript directly, correct?

**Comment by kwoxford** [comment]
The end to end sample is huge and complex. It’s not comparable with the simple starter scripts you’ve given for React and Vue
