### ISSUE TITLE
Maybe some RehydratedProps member types are wrong 

### ISSUE THREAD

**Issue by masarusanjp** [awslabs/aws-mobile-appsync-sdk-js#66]
Current `RehydratedProps` definition is below.

```
export interface RehydratedProps {
    render?: ((props: { rehydrated: boolean }) => React.ReactNode);
    children?: React.ReactChildren;
    loading?: React.ComponentType<any>;
    style?: any;
}
```

But `Rehydrated.propTypes` defines each as` PropTypes.node`.
Also, `render ()` returns the passed values ​​of `children` and` loading`.
Since `render ()` expects `ReactNode` to be returned, it does not work as expected with the type defined by` PropTypes`.
If implementation is correct, 
I think `children` and `loading` type should be React.ReactNode.

**Comment by drdgvhbh** [comment]
I'm also having this error. @masarusanjp solution seems to work.

**Comment by elorzafe** [comment]
Hi @masarusanjp @drdgvhbh this PR #206 should have fix the issue. Did you try the latest version?

Thanks!

**Comment by masarusanjp** [comment]
Sorry, I missed the mention 🙇 
#206 is worked for me. 
Thank you !
