### ISSUE TITLE
Dependency on react?

### ISSUE THREAD

**Issue by CodySwannGT** [awslabs/aws-mobile-appsync-sdk-js#668]
We just tried to update aws-appsync from 3.0.3 to 4^ and couldn't because there is a dependency now on react?

That seems like it has to be a bug.

**Comment by sidathm** [comment]
Can you please share the package.json file in your working project?

**Comment by david-mcafee** [comment]
@CodySwannGT - I tested this and I was able to successfully build using version 4.1.9 of `aws-appsync` in a non-React app without React as a dependency. Could you please share your `package.json`? Thank you!

**Comment by david-mcafee** [comment]
@CodySwannGT - closing this ticket as we have not heard back from you. If you need further assistance, please let us know!
