### ISSUE TITLE
Is a JWT token for API queries mandatory if you want to use Amazon Cognito User Pool?

### ISSUE THREAD

**Issue by talkhot** [awslabs/aws-mobile-appsync-sdk-js#68]
For the sake of example I use a simple case.
I have a blog (react-website) who is publicly accessible. Only registered user can create posts and un-registered visitors should be able to just read the blog.

For this case I like to use the **Amazon Cognito User Pool** as authorization type, so once the user is logged-in I can grant the user acces based on there Cognito Group for example a Editor and Admin group.

It seems I have to provide a valid JWT user token to query the API so I can't show blog posts to users who are not logged-in and registered. 
Can I use the **Amazon Cognito User Pool** as authorization type and still read from the API when a user is not logged-in? If not what would be the recommended way to deal with this I guess quite common use-case?

**Comment by alez007** [comment]
Yes, go to federated identities and create new identity pool. Make sure you allow "Unauthenticated identities " and make sure you add your user pool id and app id in the "Authentication providers" section under Cognito provider. 

This will allow you to have two iam roles: one for guests and one for authenticated users. You can differentiate between them in your appsync resolvers by reading that information with $context.identity.

**Comment by elorzafe** [comment]
@rarira did you signin first?, I used access token instead of idToken

```
const client = new AWSAppSyncClient({
  url: aws_appsync_graphqlEndpoint,
  region: aws_appsync_region,
  auth: {
    type: AUTH_TYPE. AMAZON_COGNITO_USER_POOLS,
    // COGNITO USER POOLS
    jwtToken: async () => (await Auth.currentSession()).getAccessToken().getJwtToken(),
  }
});
```

Take a look on this [sample](https://github.com/aws-samples/aws-amplify-graphql)

**Comment by JoshuaMorleyWoodside** [comment]
I cant find any examples that dont use amplify to get the jwt token in the AppSyncClient initialisation
Can anyone provide links or explain/include code on how to perform this initialisation in environments amplify cannot be used? 
tagging as issue is closed: @elorzafe
