### ISSUE TITLE
Node.js example has been removed from documentation

### ISSUE THREAD

**Issue by davthedev** [awslabs/aws-mobile-appsync-sdk-js#690]
I am using AppSync from a Node.js environment in Lambda.

There was a Node.js example in the documentation until recently. I used it to get started.
Are we supposed to use a different approach with those changes? Is the use of this SDK discouraged from such environments now?

**Comment by david-mcafee** [comment]
Closing this issue. @davthedev please reopen if you need further help, thanks!
