### ISSUE TITLE
JS SDK vs Amplify SDK

### ISSUE THREAD

**Issue by zachjonesnoel** [awslabs/aws-mobile-appsync-sdk-js#696]
>  Note: If your issue/feature-request/question is regarding the AWS AppSync service, please log it in the 
  [official AWS AppSync forum](https://forums.aws.amazon.com/forum.jspa?forumID=280&start=0)

**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Which versions and which environment (browser, react-native, nodejs) / OS are affected by this issue? Did this work in previous versions?**

How is this SDK different from Amplify SDK. That has a good way to leverage the authorization from Cognito but I was trying to understand the features of this SDK.

**Comment by elorzafe** [comment]
@zachjonesnoel 

The biggest difference, is that AppSync SDK is compatible with Apollo. Amplify client also has support for DataStore which is our suggested way to create offline first apps.

Thanks!

**Comment by zachjonesnoel** [comment]
Thanks @elorzafe for clarifying. I will try the SDK out, have always been Amplify SDK user.
