### ISSUE TITLE
AWS Resources are not created when we use JS SDK

### ISSUE THREAD

**Issue by sid88in** [awslabs/aws-mobile-appsync-sdk-js#7]
Not sure if this is expected behavior but new aws resources are not automatically created when we run JS SDK code

[Reference](https://github.com/serverless/serverless-graphql/blob/master/app-backend/appsync/dynamo/deploy-dynamo.js)

**Comment by undefobj** [comment]
Do you mean DynamoDB tables from a schema? That's a console only feature at this point.

**Comment by sid88in** [comment]
correct. Ok it makes sense now ;)
