### ISSUE TITLE
Subscribe only available for AWS AppSync endpoint

### ISSUE THREAD

**Issue by phucnguyencong** [awslabs/aws-mobile-appsync-sdk-js#717]
I get issues when using @apollo/client: 3.5.10, aws-appsync-auth-link:  3.0.7,  aws-appsync-subscription-link: 3.0.10. 
There is my config 
```
import { ApolloClient, ApolloLink, createHttpLink, InMemoryCache } from '@apollo/client';
import { createAuthLink } from 'aws-appsync-auth-link';
import { createSubscriptionHandshakeLink } from 'aws-appsync-subscription-link';
// Config
import { AWS_APPSYNC } from '../config';

const { graphqlEndpoint, region, apiKey } = AWS_APPSYNC;
const auth = {
  type: AWS_APPSYNC.authenticationType,
  apiKey: apiKey,
};

const httpLink = createHttpLink({ uri: graphqlEndpoint });
const link = ApolloLink.from([
  // @ts-ignore
  createAuthLink({ graphqlEndpoint, region, auth }),
  // @ts-ignore
  createSubscriptionHandshakeLink({ graphqlEndpoint, region, auth }, httpLink),
]);

export const client = new ApolloClient({
  link,
  cache: new InMemoryCache(),
});
```

and I am using 
```
  const {
    data: subscription_message_data,
    loading: subscription_message_loading,
    error: subscription_message_error
  } = useSubscription(
    SUBSCRIPTION_NEW_MESSAGE, {
      variables: { conversationId: conversationId }
    });
```
But I got an error form useSubscription is: "Subscribe only available for AWS AppSync endpoint"

Does anyone have experience with this issue?

**Comment by iartemiev** [comment]
Hi, are you still experiencing this issue? If so, have you tried updating to the latest version of the libary - 4.1.9?

**Comment by phucnguyencong** [comment]
> Hi, are you still experiencing this issue? If so, have you tried updating to the latest version of the libary - 4.1.9?

The main issue from my configuration and I had fixed without upgrade version

**Comment by phucnguyencong** [comment]
I was resolve this issue

**Comment by Ishara-Mee** [comment]
Hi @phucnguyencong ,  Can you please explain the configuration issue you had ? Im having the same problem
