### ISSUE TITLE
How can I use it inside aws lambda ?

### ISSUE THREAD

**Issue by ameerulislam** [awslabs/aws-mobile-appsync-sdk-js#729]
will Appollo client work with in aws lambda? I want to do Appsync graphql operations from my lambda. I can't find any way to do it.

**Comment by iartemiev** [comment]
Here's the recommended approach for interacting with AppSync from Lambda: https://docs.amplify.aws/lib/graphqlapi/graphql-from-nodejs/q/platform/js/
