### ISSUE TITLE
 Cannot find module: '@aws-sdk/util-endpoints'

### ISSUE THREAD

**Issue by jsmith213561** [awslabs/aws-mobile-appsync-sdk-js#734]
I've checked [AWS Forums](https://forums.aws.amazon.com/) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
 I've searched for [previous similar issues](https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues) and didn't find any solution.

### **Describe the bug :**
I have got this error when AWS amplify create a build for my React App

![image](https://user-images.githubusercontent.com/97633012/197037613-902b6f3b-c081-4d0d-ae41-f9e3672f321e.png)

`./node_modules/aws-appsync/node_modules/@aws-sdk/client-s3/dist-es/endpoint/endpointResolver.js
 Cannot find module: '@aws-sdk/util-endpoints'. Make sure this package is installed.
 You can install this package by running: npm install @aws-sdk/util-endpoints.`

### **NPM version number**
`aws-appsync": "^4.1.5`

### **Details of the browser/Node.js/React version**
16.9.0

### **Reproduction Steps**
Just install `@aws-sdk/aws-appsync `and create a build using `yarn build` or `npm run build` you will be able to reproduce this

### **Observed Behavior**
Breaks

### **Expected Behavior**
Should not break.

### **Possible Solution**
No response

### **Additional Information/Context**
No response

**Comment by iartemiev** [comment]
This was fixed in 3.193. Closing
