### ISSUE TITLE
View.propTypes.style crashes release app

### ISSUE THREAD

**Issue by DmytroT** [awslabs/aws-mobile-appsync-sdk-js#75]
The title of the issue describing the line in the code that causes iOS/Android app crashes in Release mode.
https://github.com/awslabs/aws-mobile-appsync-sdk-js/blob/master/packages/aws-appsync-react/src/rehydrated-rn.tsx
line 54

You have a pull request available at https://github.com/awslabs/aws-mobile-appsync-sdk-js/pull/58 that should fix this issue
Please integrate it ASAP.

Thanks!

**Comment by manueliglesias** [comment]
Closed by #58
