### ISSUE TITLE
Paho not defined

### ISSUE THREAD

**Issue by suprsidr** [awslabs/aws-mobile-appsync-sdk-js#76]
the Paho-client used in this project tries to declare Paho globally:
`if (typeof Paho === "undefined") {
	Paho = {};
}`
webpack doesn't seem to handle this correctly and I get an error in my bundle.

> Paho not defined node_modules/paho-client/src/mqttws31.js line 83

The Paho client used in the aws-iot-device-sdk does not suffer from this issue.

**Comment by undefobj** [comment]
Are you trying to use NodeJS?

**Comment by suprsidr** [comment]
I'm using this in the browser

**Comment by undefobj** [comment]
Ok great, this seems like a webpack issue. One thing you might want to try is to run the starter app https://github.com/aws-samples/aws-mobile-appsync-events-starter-react and then eject. This was built with Create React App and if you eject you'll see how react-scripts configures webpack.

**Comment by suprsidr** [comment]
The Paho client used in the aws-iot-device-sdk does not suffer from this issue.

it uses https://github.com/mqttjs/MQTT.js

**Comment by undefobj** [comment]
Paho isnt the same thing as MQTT.js, they're separate implementations. Paho is the MQTT reference implementation and works in both web JavaScript applications as well as React Native, whereas MQTT.js does not.
