### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Xiphe** [awslabs/aws-mobile-appsync-sdk-js#79]
Hey there. Really looking forward to use AppSync in my product.

For development and testing it would be awesome to have mocking capabilities on the API. Apollo itself makes this really easy.

Are there any best practices? I would really appreciate if this project would have unit tests that I could use as an example.

**Comment by manueliglesias** [comment]
Hi @Xiphe 

We've been slowly adding some tests to this public repo [here](https://github.com/awslabs/aws-mobile-appsync-sdk-js/tree/master/packages/aws-appsync/__tests__)

We'll continue adding more as bug fixes / features are added

Thanks for trying the SDK!
