### ISSUE TITLE
Uncaught (in promise) Error: GraphQL error: Variable 'id' has coerced Null value for NonNull type 'ID!'

### ISSUE THREAD

**Issue by ceich** [awslabs/aws-mobile-appsync-sdk-js#83]
I am seeing one of my queries (`getAccount(id:ID!):Account`) being called with null (or at least "coerced Null") but it's not being called from my code AFAICT. The trigger for this error is creation of an account member (which all works, both optimistic response and network call), and then rendering the "view account" component, which is wrapped by the above query.

The coerced Null call is in response to the network call completing (I tested this by turning off WiFi before clicking Save, then waiting 10 seconds and turning WiFi on; the error only appears after the network is back). This is the only stack trace I have:

```
Uncaught (in promise) Error: GraphQL error: Variable 'id' has coerced Null value for NonNull type 'ID!'
    at new ApolloError (ApolloError.js:34)
    at QueryManager.js:273
    at QueryManager.js:654
    at Array.forEach (<anonymous>)
    at QueryManager.js:653
    at Map.forEach (<anonymous>)
    at QueryManager../node_modules/aws-appsync/node_modules/apollo-client/core/QueryManager.js.QueryManager.broadcastQueries (QueryManager.js:648)
    at Object.next (QueryManager.js:682)
    at SubscriptionObserver.next (zen-observable.js:158)
    at dedupLink.js:49
    at Array.forEach (<anonymous>)
    at Object.next (dedupLink.js:49)
    at SubscriptionObserver.next (zen-observable.js:158)
    at SubscriptionObserver.next (zen-observable.js:158)
    at SubscriptionObserver.next (zen-observable.js:158)
    at SubscriptionObserver.next (zen-observable.js:158)
    at httpLink.js:78
```

What can I do to narrow this down, or get more debug info?

**Comment by undefobj** [comment]
Hi, this sounds like when you're calling the query no `ID` type is being provided. Can you provide the client code? It should be something like `query { getAccount(123){ id }` where 123 is the ID. Many times people use variables here for the ID which might be null as your application code may not be populating it correctly. You can always prove this by hardcoding a valid ID.

**Comment by ceich** [comment]
I've used console.log() to ensure that all the calls from my code are providing a valid id.

I think what's happening is a Member with a null Account is coming back from the server, since it happens whenever I create or delete a Member (which provokes a re-query of Account to get the updated members field). Note that I was getting a different error when the Member had non-nullable fields, see this [forum post](https://forums.aws.amazon.com/thread.jspa?threadID=277513&tstart=0) for the schema.

Client code is modeled on the sample app, with events/comments => accounts/members.

**Comment by undefobj** [comment]
If the client is passing valid arguments then try to run the query with those arguments on the Queries tab of the AppSync console. If you get the same error there then the issue is in the GraphQL schema or potentially the resolver for a field not returning a value when the field isn't nullable

**Comment by ceich** [comment]
The client code is running a mutation (either create or delete of a Member), but mentions the query in the `refetchQueries` and `update` properties of the graphql() config.options:
```
  graphql(MutationDeleteMember, {
    alias: 'MutationDeleteMember',
    options: {
      refetchQueries: [{ query: QueryGetAccount }],
```
I just realized that `refetchQueries` is not including the `variables` property! It should be:
```
      refetchQueries: ({ data: { deleteMember: { account: { id } } } }) => (
        [{ query: QueryGetAccount, variables: { id } }]
      ),
```
Problem solved. Thanks for your replies!
