### ISSUE TITLE
Can this be used without dynamoDB/VTL?

### ISSUE THREAD

**Issue by honkskillet** [awslabs/aws-mobile-appsync-sdk-js#85]
This is more of a Question than an issue.  I like the offline/sync capabilities of AppSync but don't really want to be doing my backend coding in VTL.  Can these frontend libraries be used with a GraphQL/Mongo backend?

**Comment by undefobj** [comment]
Yes - you can use AppSync with data sources of DynamoDB, Amazon Elasticsearch and AWS Lambda. With Lambda as a data source you have full control to pass the context object through and use any language of your choice. Here is a tutorial for you to get started: https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-lambda-resolvers.html

**Comment by philohelp** [comment]
I use dynamoose with Lambda for some cases, which is inspired by mongoose. But I must say that with VTL utils and docs things become more trivial.
