### ISSUE TITLE
Linking DynamoDB tables in GraphQL AppSync

### ISSUE THREAD

**Issue by sebastienfi** [awslabs/aws-mobile-appsync-sdk-js#86]
Hi !

I'm not sure this is the right place to post this, but the AWS AppSync forum seems dead.

Let's consider the following sample schema in AppSync :

```gql
# A City
type City {
  cityId: ID!
  name: String!
  streets(first: Int, after: String): StreetConnection
  mainStreet: Street
}
# A Street in the city
type Street {
  cityId: ID!
  streetId: ID!
  name: String!
  trees(first: Int, after: String): TreeConnection
}
type StreetConnection{
  items: [Street]
  nextToken: String
}
# A Tree in the street
type Tree {
  streetId: ID!
  treeId: ID!
  name: String!
  leavesNumber: Int!
  street: Street
}
type TreeConnection{
  items: [Tree]
  nextToken: String
}
```

The types are each a DynamoDB table : 
  - Type City : Table_City (key: cityId)
  - Type Street : Table_Street (key: cityId, sort: streetId)
  - Type Tree : Table_Tree (key: streetId, sort: treeId)

Which modification to the schema and/or resolvers should I produce in order to be able to make the following GraphQL query ?
```gql
query GetCityWithTrees($cityId: ID!) {
  getCityWithTrees(cityId: $cityId) {    
    name
    streets {
      items {
        name
        trees {
          items {
            name 
            leavesNumber     
          }
        }
      }
    }
  }
}
```

Same question if I want to execute the following query :
```gql
query GetTree($streetId: ID!, $treeId: ID!) {
  getTree(streetId: $streetId, treeId: $treeId) {    
    name
    street {
      name       
    }
  }
}
```

Any help appreciated :)

**Comment by haverchuck** [comment]
Hi @sebastienfi -
From what I can tell your basic schema is ok.  I've rebuilt it in AppSync (along with the three DynamoDB tables) and was able to run your 'getCityWithTrees' query in the AppSync GUI without any issues.  The response I received looks like this:
```
{
  "data": {
    "getCity": {
      "name": "Portland",
      "streets": {
        "items": [
          {
            "name": "Burnside",
            "trees": {
              "items": [
                {
                  "name": "Douglas Fir",
                  "leavesNumber": 1000
                }
              ]
            }
          }
        ]
      }
    }
  }
}
```
Does that look like what you wanted?

I suspect that the issue might be with your schema's resolvers.  Please make sure that you have a resolver for each property that should resolve to a '{attribute}Connection'.  

You may want to check out the automated tools that the AppSync GUI provides, which will set up a lot of these for you.  For example, if you provide the basics of your schema you will be given a 'Create Resources' option that will provision DynamoDB tables, queries, mutations and their accompanying resolvers for you.

Let us know if this doesn't help!
