### ISSUE TITLE
deploy appsync-sdk-js to ionic real device

### ISSUE THREAD

**Issue by selfordering** [awslabs/aws-mobile-appsync-sdk-js#88]
Dear aws appsync developer 

I am newbie for this solutions.
I have try to use this module to ionic app.
it is doing well in web-browser mode.
however, when I deploy to real device (ios iPhone8plus and iPhone6S) , it seems like device cannot access to graphQl entpoint.
is there any restriction on this module to deploy to real device?

anyway, I am also using aws Cognito. It is playing well role.

Thank you

**Comment by marcoturi** [comment]
This probably an issue on cordova side. Check your config.xml.

**Comment by selfordering** [comment]
Thanks @marcoturi  for you advice.
let me check it . then I will share you again
thank U

**Comment by manueliglesias** [comment]
Please feel free to re-open if needed
