### ISSUE TITLE
componentWillMount/componentWillReceiveProps is deprecated

### ISSUE THREAD

**Issue by ajmakhl** [awslabs/aws-mobile-appsync-sdk-js#94]
I am getting a warning with ```componentWillMount``` and ```componentWillReceiveProps```.

<img width="488" alt="screen shot 2018-04-07 at 11 04 43 am" src="https://user-images.githubusercontent.com/17507288/38456531-af8ba4da-3a53-11e8-8140-c5ab6590aaa6.png">

<img width="490" alt="screen shot 2018-04-07 at 11 05 35 am" src="https://user-images.githubusercontent.com/17507288/38456536-b490f71e-3a53-11e8-8a2f-f1612be0724a.png">

**Comment by AlpacaGoesCrazy** [comment]
This is part of the React 16.3.0 update. Those methods will be removed somewhere around React 17.0.0
But we have a replacement for those: `static getDerivedStateFromProps(nextProps, prevState)` and `getSnapshotBeforeUpdate(prevProps, prevState)`
Hopefully Appsync team will update to new lifecycle methods soon
React blogpost regarding this:
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html
